### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by aa00wb** [Der-Henning/tgtg#106]
403 Error popped out again
Solution found somewhere on the web : 
USER_AGENTS = [
    "TGTG/22.5.5 Dalvik/2.1.0 (Linux; U; Android 9; SM-G955F Build/PPR1.180610.011)"
]

**Comment by Der-Henning** [comment]
Hi @aa00wb.
Thank you. Updated `USER_AGENTS` in 632676d4e1ec067e2ff349feb7ab7c16df5b4e4e.
Latest Docker Image already includes the fix. New releases will follow asap.

**Comment by Der-Henning** [comment]
Fixed in Release 1.10.4
