### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by ottoman4290** [Der-Henning/tgtg#116]
I get the following error code when running:

Jul 01 15:41:54 pi systemd[1]: Started TooGoodToGo.
Jul 01 15:41:55 pi python3[10189]: Traceback (most recent call last):
Jul 01 15:41:55 pi python3[10189]:   File "/home/pi/Desktop/tgtg-1.11.0/src/scanner.py", line 33, in <module>
Jul 01 15:41:55 pi python3[10189]:     class Scanner():
Jul 01 15:41:55 pi python3[10189]:   File "/home/pi/Desktop/tgtg-1.11.0/src/scanner.py", line 115, in Scanner
Jul 01 15:41:55 pi python3[10189]:     def _get_favorites(self) -> list[Item]:
Jul 01 15:41:55 pi python3[10189]: TypeError: 'type' object is not subscriptable
Jul 01 15:41:55 pi systemd[1]: 2good2go.service: Main process exited, code=exited, status=1/FAILURE
Jul 01 15:41:55 pi systemd[1]: 2good2go.service: Failed with result 'exit-code'.

What am I doing wrong?

**Comment by Der-Henning** [comment]
I guess everything is working now? Closing.
Feel free to reopen or create a new Issue if you have any problems.

**Comment by ottoman4290** [comment]
Thank you for your support.
