### ISSUE TITLE
Telegram chat id not working

### ISSUE THREAD

**Issue by p3t3r** [Der-Henning/tgtg#148]
Hello,

I'm having an issue with the chat id of Telegram (TELEGRAM_CHAT_IDS).
I've configured a Telegram bot and created a group in Telegram with that bot, but tgtg notifier sends the message directly and not in this group.
I've issued a test POST via:
curl -X POST "https://api.telegram.org/botX:Y/sendMessage" -d "chat_id=-12345&text=my sample text"
Providing that same chat id, and that works.
Maybe it is because of the minus sign?

**Comment by Der-Henning** [comment]
Hi @p3t3r.
Can you confirm, that you put the correct chat_id in your `config.ini` / `docker-compose.yml`?
I tried to reproduce your error and it worked just fine with group and direct chat.

**Comment by p3t3r** [comment]
It's working now, I've recreated the docker container.
It didn't work after restarting the container.

Thanks.
