### ISSUE TITLE
DEBUG    Failed to find locale Dutch_Netherlands

### ISSUE THREAD

**Issue by RickMartens23** [Der-Henning/tgtg#149]
Hi,

i did fill in the config.ini file but keep getting the same error, what did i do wrong?

Grz. Rick

2022-09-09 13:43:00 INFO     Loaded config from config.ini
2022-09-09 13:43:00 INFO     Debugging mode enabled
2022-09-09 13:43:00 DEBUG    Failed to find locale Dutch_Netherlands
2022-09-09 13:43:00 DEBUG    Attempting to load en_US as fallback

**Comment by Der-Henning** [comment]
Hi @RickMartens23.
Does the scanner exit or crash after this message? Or does it start working?
Can you post your `config.ini`? Of cause with anonymised keys and personal information.

**Comment by RickMartens23** [comment]
it looks like it starts
Hope i didn't remove to much info ;)
[config(2).txt](https://github.com/Der-Henning/tgtg/files/9535245/config.2.txt)

**Comment by Der-Henning** [comment]
When it starts you should see debugging messages like this:
````
2022-09-09 14:13:56 DEBUG    https://apptoogoodtogo.com:443 "POST /api/item/v7/ HTTP/1.1" 200 None
2022-09-09 14:13:56 DEBUG    new State: {'431440': 0, '325124': 0, '9999': 0, '91344': 0, '671585': 0}
2022-09-09 14:13:55 INFO     Active on schedule: Every Minute, Monday to Sunday
````

There is no problem with your config. The script to describe the active schedule uses your localization and is not able to find `Dutch_Netherlands`. So it falls back to english. Should work and cause no further problems.

But if it doesn't continue with the above mentioned messages we have to investigate ...

**Comment by RickMartens23** [comment]
[scannerlog.txt](https://github.com/Der-Henning/tgtg/files/9535477/scannerlog.txt)

I think it won't start, the debug doesn't show that message

**Comment by Der-Henning** [comment]
Release [v1.12.1](https://github.com/Der-Henning/tgtg/releases/tag/v1.12.1) should fix the problem.

**Comment by RickMartens23** [comment]
thanks, will test it again.
keep up the good work!

**Comment by RickMartens23** [comment]
[scannerlog2.txt](https://github.com/Der-Henning/tgtg/files/9535875/scannerlog2.txt)

I get an SMTP error, is this error because of my email settings in the config.ini?

**Comment by Der-Henning** [comment]
Gmail doesn't allow you to login with your regular password without 2-factor authentication. To login with an external app you have to create an app password. For more information see the google documentation below:

https://support.google.com/accounts/answer/185833?hl=en

**Comment by Der-Henning** [comment]
Closing.
Feel free to reopen or create a new issue if you have any problems.
