### ISSUE TITLE
Link to specific item

### ISSUE THREAD

**Issue by p3t3r** [Der-Henning/tgtg#154]
Feature request: would it be possible to get an app link to a specific item in the notification?
Now I get the notification, but have to open the app, navigate to favorites and selecting the item. This often results in a sold out when trying to pay.

Even an app link to the favorites in the tgtg app would be useful.

**Comment by Der-Henning** [comment]
Hi @p3t3r.
This is already possible. But the link only works on android.
You can modify the body of the notifications and include `https://share.toogoodtogo.com/item/${{item_id}}`.
See [config.sample.ini](https://github.com/Der-Henning/tgtg/blob/main/src/config.sample.ini) for details.

**Comment by p3t3r** [comment]
Ok, that's nice, the link example wasn't in the docker-compose.yml.

But I can't get the TELEGRAM_BODY example working in docker-compose.yml, getting syntax error:
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 42, column 135

using:
      - TELEGRAM_BODY=                               'TELEGRAM_BODY=*$${{display_name}}*\n*Available*: $${{items_available}}\n*Rating*: $${{rating}}\n*Price*: $${{price}} $${{currency}}\n*Pickup*: $${{pickupdate}}\n*Link*: https://share.toogoodtogo.com/item/${{item_id}}'

**Comment by Der-Henning** [comment]
You doubled `TELEGRAM_BODY=`.
In some cases (Portainer) you have to add ``{{` ... `}}``.
try
````
- 'TELEGRAM_BODY=*$${{display_name}}*\n*Available*: $${{items_available}}\n*Pickup*: $${{pickupdate}}\n*Location*: $${{pickup_location}}\n*Price*: $${{price}} $${{currency}}'
````
or
````
- 'TELEGRAM_BODY={{`*$${{display_name}}*\n*Available*: $${{items_available}}\n*Pickup*: $${{pickupdate}}\n*Location*: $${{pickup_location}}\n*Price*: $${{price}} $${{currency}}`}}'
````

**Comment by p3t3r** [comment]
With that change I now get the error:

`ERROR: Invalid interpolation format for "environment" option in service "app": "TELEGRAM_BODY={{`*$${{display_name}}*\n*Available*: $${{items_available}}\n*Rating*: $${{rating}}\n*Price*: $${{price}} $${{currency}}\n*Pickup*: $${{pickupdate}}\n*Link*: https://share.toogoodtogo.com/item/${{item_id}}`}}"`

**Comment by Der-Henning** [comment]
Added example to `docker-compose.yml`. [fbc2792](https://github.com/Der-Henning/tgtg/commit/fbc2792dccca914ccea196826388f90e77a78804)
Thank you for the hint.

Are you using docker-compose directly or a stack on docker swarm or some docker management software like portainer? Every case is special in these terms ...

**Comment by p3t3r** [comment]
Using docker-compose command line:
sudo docker-compose up -d

**Comment by p3t3r** [comment]
Yes, that was it, thank you very much for the fast replies!

**Comment by Der-Henning** [comment]
You are welcome.
