### ISSUE TITLE
Which aws free tier should I choose?

### ISSUE THREAD

**Issue by swiezaczek** [Der-Henning/tgtg#160]
I am newbie, please help me to choose correct free tier aws. I would like to install it there for automated telegram notifications. Can you baby step it for me, please? Thanks

**Comment by Der-Henning** [comment]
Hi @swiezaczek.
I am sorry I cannot give you a full walkthrough for the deployment on AWS. But the hardware requirements for this tool are very low so the smallest type available should be sufficient. 
If you need help creating an AWS instance please refer to the official documentation. There are also many tutorials on the web.

**Comment by swiezaczek** [comment]
Ok, I have managed to get it to work, Have you ever heard of similar app Foodsi? I think its available in Poland only, however I am not sure. Any chance You Will update your bot to work with foodsi as well?

**Comment by Der-Henning** [comment]
1. Sorry I cannot help you with Heroku. Here is a tutorial that might help: https://github.com/michaelkryukov/heroku-python-script
2. No, but feel free to fork this project and integrate the Foodsi API. Your contribution will be welcome. 
3. The `helper.py` is not part of the main program and only provides some helping functions to manage the tgtg account. The intended use of the TGTG Scanner is that you add all items you want to get notifications from in the official TGTG App. The scanner will automatically watch the favorites of the provided TGTG account.

**Comment by Der-Henning** [comment]
With d230230edf9dc2aa36728ad178105f8f3c2caaf7 I added a `Procfile` for Heroku deployment. If you fork this repository you can connect it to a Heroku app. For configuration you have to add the environment variables as described in `docker-compose.yml`.

**Comment by swiezaczek** [comment]
Thank you
