### ISSUE TITLE
Fails to deploy to AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by rauner** [Der-Henning/tgtg#161]
Docker runs locally but fails to deploy to AWS EB:

/var/log/eb-docker/containers/eb-current-app/eb-stdouterr.log
----------------------------------------
app_1  | 2022-09-25 09:30:48 ERROR    Configuration Error - Invalid TGTG configuration
app_1  | 2022-09-25 09:30:48 ERROR    You must provide at least email or access_token, refresh_token and user_id
app_1  | 2022-09-25 09:30:48 INFO     
app_1  | 2022-09-25 09:30:48 INFO        )( ( (_ \  )( ( (_ \  \___ \( (__ /    \/    //    / ) _)  )   / 
app_1  | 2022-09-25 09:30:48 INFO       ____  ___  ____  ___    ____   ___   __   __ _  __ _  ____  ____  
app_1  | 2022-09-25 09:30:48 INFO       (__) \___/ (__) \___/  (____/ \___)\_/\_/\_)__)\_)__)(____)(__\_) 
app_1  | 2022-09-25 09:30:48 INFO      (_  _)/ __)(_  _)/ __)  / ___) / __) / _\ (  ( \(  ( \(  __)(  _ \ 
app_1  | 2022-09-25 09:30:48 INFO     Â©2021, Henning Merklinger
app_1  | 2022-09-25 09:30:48 INFO     For documentation and support please visit https://github.com/Der-Henning/tgtg
app_1  | 2022-09-25 09:30:48 INFO     Loaded config from environment variables
app_1  | 2022-09-25 09:30:48 INFO     Version 1.12.1
app_1  | 2022-09-25 09:30:48 WARNING  No token files in token path.
Attaching to 
Attaching to current_app_1
current_app_1 exited with code 1

---------------------------------------
/var/log/eb-engine.log
----------------------------------------

...

2022/09/25 07:30:48.835967 [INFO] Running command /bin/sh -c docker rmi `docker images -aq`
2022/09/25 07:30:49.175416 [INFO] Untagged: derhenning/tgtg:latest
Untagged: derhenning/tgtg@sha256:a2f03250fc3269572c8dcffd8df3405ba143aac1f5f78cbfaf62e2bf7c8fb419

...

2022/09/25 07:30:49.175434 [INFO] restore docker image name with command: docker tag 2ca17fd10f46 derhenning/tgtg:latest
2022/09/25 07:30:49.175448 [INFO] Running command /bin/sh -c docker tag 2ca17fd10f46 derhenning/tgtg:latest
2022/09/25 07:30:49.203308 [INFO] Error response from daemon: No such image: 2ca17fd10f46:latest

...

**Comment by Der-Henning** [comment]
Hi @rauner.
The Error indicates you didn't provide any TGTG account information. Did you use the environment variables for configuration?

**Comment by rauner** [comment]
I put the email in the .env. Will try using the config.ini

**Comment by Der-Henning** [comment]
The .env will not automatically be read. Configuration by file is done with the config.ini. But deploying on AWS I recommend configuring the environment variables in the settings of the instance.

**Comment by rauner** [comment]
> 

originally used this approach which throws the same error of TGTG account information.

Weird that the logs indicate that the other env variables are set:
app_1  | 2022-09-26 11:45:06 INFO     Active on schedule: * 7-23 * * 1-7

Will try setting the credentials manually.
