### ISSUE TITLE
Telegram accounts

### ISSUE THREAD

**Issue by Jeannot78140** [Der-Henning/tgtg#169]
Hi,

Can we add several telegram accounts for notifications ? If yes, may you give an example please?

Many thanks

Jean

**Comment by Der-Henning** [comment]
Hi @Jeannot78140,
At the moment you can only add one bot. But you can include multiple chat_ids as comma separated list or use a group chat with multiple users.
Does this help you?

**Comment by Jeannot78140** [comment]
Actually, I created a bot, by botfather. When a create a chat room and invite my bot, the bot don't send any notification. (I know, I'm a noob...)
Did I  make a mistake? Or isn't it possible ?

Other problem : Pushsafer sent me this message : "an error has occured. There are not enough API calls available. To expand your messages capacity, go to your pushsafer dashboard and press the cart button"
Does it mean that the only way to use pushsafer notifications is to pay ?

**Comment by Der-Henning** [comment]
Yes, PushSafer is a payed service. You only have some Notifications for free when you create a new account.

You received a token from the botfather that identifies your bot. Now modify you `config.ini` in the `TELEGRAM` section as follows:
````
[TELEGRAM]
enabled = true
token = 123456789:bdsifjhjisahfjhsd <<<--- the bot token
````
Ignore or leave blank the option `chat_ids`. After starting the scanner you will be guided through a process, that will fetch the correct chat id. When you want want to use multiple chat ids you have to grab it manually though.

**Comment by Jeannot78140** [comment]
Thanks Henning, that's right . it effectively works by replacing my chat_id with the chat_id of the group where I invited my bot 👍
