### ISSUE TITLE
Function to save favourites to file

### ISSUE THREAD

**Issue by swiezaczek** [Der-Henning/tgtg#178]
... and function to upload them all from the file to the account (useful when you want to make scrapper account from your original account). Now you need to do it manually and its pain in the ass when you have many favourites.

**Comment by WhogetCharles321** [comment]
Yo
pomógł byś mi z tym skanerem może? 
Niezbyt potrafię go ogarnąć.

**Comment by WhogetCharles321** [comment]
Yo
pomógł byś mi z tym skanerem może?
Niezbyt potrafię go ogarnąć.

**Comment by Der-Henning** [comment]
This is not that difficult. I would integrate this in the `helper.py`. Most needed functions are already included. If you want you can try to implement it yourself and create a pull request. I will try to help you and review your code.

I for myself don't have the time to implement new features at the moment.

**Comment by swiezaczek** [comment]
Unfortunately I know nothing about coding. Any books/tutorials you can recommend?

**Comment by Der-Henning** [comment]
In terms of books I highly recommend the books published by O'Reilly. https://www.oreilly.com/library/view/learning-python-5th/9781449355722/ is very good.

**Comment by Der-Henning** [comment]
With [96d24e8](https://github.com/Der-Henning/tgtg/commit/96d24e8ed115bdbd4e092bf5d96750495a37263a) you can retrieve the IDs of you favorites with `scanner -F`. Then change the account information to your second account and add the favorites with `scanner -a id1 id2 id3 ...`. Just copy the previously retrieved list.

I didn't create a new release for now but I would appreciate any feedback if you test the current build found under https://github.com/Der-Henning/tgtg/suites/8911534246/artifacts/408145366

**Comment by swiezaczek** [comment]
Thanks. I dont use releases, but work with cmd, but It works perfectly Thank you again
