### ISSUE TITLE
No notifications on Sunday with CRON setup

### ISSUE THREAD

**Issue by swiezaczek** [Der-Henning/tgtg#180]
`ScheduleCron = * 7-23 * * 1-7`

Whats wrong with my cron settings? I've not received any notifications today until I deleted my cron settings.
For me it seems set up allright - 7.00-23.59 Monday to Sunday.

**Comment by Der-Henning** [comment]
If you run the scanner with debugging enabled the scanner displays the current state of you favorite bags. If the scanner is disabled by the cron setting no state is displayed.
If you only want the scanner to run in a specific time range you can also set
`ScheduleCron = * 7-23 * * *`

**Comment by Der-Henning** [comment]
[9d651e8](https://github.com/Der-Henning/tgtg/commit/9d651e8eaf2f6e814146f2a7e639609c55b6292f) now displays an information in the log if the scanner gets dis-/enabled by the cron scheduler.

**Comment by swiezaczek** [comment]
No state of favourite bags was displayed, so the scanner was off. 

and this:
``import datetime from datetime
print(datetime.now())``
gives me syntax error

**Comment by swiezaczek** [comment]
With `ScheduleCron = * 7-23 * * *` everything works fine
