### ISSUE TITLE
run scanner in ubuntu terminal

### ISSUE THREAD

**Issue by Caibara** [Der-Henning/tgtg#191]
Hello Henning,

First, thanks a bunch for this great piece of tech. I love it and it's so convenient, not missing any bags anymore.

I have been using it for some days on Windows and was about to set it up on a strato vps running Ubuntu.
I did prepare the config file and transferred both files via filezilla. 

The problem I'm facing now is how to properly execute the scanner.
I tried several methods, but since the file lacks any file type, I'm completely stuck there.

It'll be greate if you could point me in the right direction.

Sorry if this may be a no-brainer, I'm not the versed in linux.

Viele Grüße
Chris

**Comment by Der-Henning** [comment]
Hi @Caibara.

Linux executables usually don't have a file extension like .exe in windows.
You can run it by just typing `./scanner`.
I would recommend creating a service that runs the scanner for you as long as the machine runs. It is also possible to use crontab and start it on system startup but that won't restart the app after a crash.
Creating a service in ubuntu is not very difficult but may depend on the actual os version you are using and there are plenty of tutorials on google.

https://www.shubhamdipt.com/blog/how-to-create-a-systemd-service-in-linux/

Regards
Henning
