### ISSUE TITLE
Stops at "scanner started..."

### ISSUE THREAD

**Issue by Mits-K** [Der-Henning/tgtg#200]
Hello, 
I'm kind of a newbie but I've managed to install the scanner first on MacOs and then on Ubuntu (when changed laptop).
Both worked fine till this morning when :

2022-11-13 14:57:22 INFO     Sending test Notifications ...
2022-11-13 14:57:22 DEBUG    https://apptoogoodtogo.com:443 "POST /api/item/v7/ HTTP/1.1" 200 None
2022-11-13 14:57:22 INFO     Scanner started ...

I use email notifications, and the usual test notification never arrived (and doesn't even seem to be created in the log).
Tried to find info here, change the config and email password with a new gmail app password. But nothing. I also tried the old MacOs scanner and seems to freeze at the same point.

Could someone help ? Any ideas ? Facing same problem?

Thanks again for this amazing tool.

**Comment by Der-Henning** [comment]
Hi @Mits-K.
Did you enable the notifier?
````ini
[SMTP]
enabled = true
````
If you post your config here I can check whats wrong. Remove mail and password of course.

**Comment by Mits-K** [comment]
Thanks for the quick response
Yes the notifier is enabled
Thought for a minute it was a time and date problem but set up cron to all day and still doesn't send.
All the other notifiers are disabled


[MAIN]
Debug = true
SleepTime = 60
ScheduleCron = * 0-23 * * 1-7
ItemIDs = 37442,34619,58267,358504
Metrics = true
MetricsPort = 8000

[TGTG]
Username = **removed**
AccessToken = **removed**
RefreshToken = **removed**
UserId = **removed**

[SMTP]
enabled = true
Host = smtp.gmail.com
Port = 465
Username = **removed**@gmail.com
Password = **removed**
TLS = false
SSL = true
Sender = **removed**@gmail.com
Recipient = **removed**@gmail.com
cron = * 0-23 * * 1-7
Subject = tgtg
Body = *${{display_name}}*\n*Available*: ${{items_available}}\n*Rating*: ${{rating}}\n*Price*: ${{price}} ${{currency}}\n*Pickup*: ${{pickupdate}}\n*Link*: https://share.toogoodtogo.com/item/${{item_id}}

**Comment by Der-Henning** [comment]
In the cron context the week starts with sunday (this is some kind of religious american view) and since lists in python start with 0 sunday corresponds to 0. You have to set the cron to 0-6 for all weekdays or 1-5 for only workdays.

**Comment by Mits-K** [comment]
Thanks that worked!
Strangly this config worked before.
Thanks again!
