### ISSUE TITLE
Proposal of new function - use of Datadome cookie

### ISSUE THREAD

**Issue by swiezaczek** [Der-Henning/tgtg#202]
New function of optional datadome cookie for authentication .

Its easy to get cookie from your phone, but there is no place where to paste it. It would be nice to have this function. If anyone is interested I can give more info.

**Comment by Der-Henning** [comment]
The latest version caches the datadome cookie the same way the tgtg tokens are stored. In the `config.ini` or in `\tokens` for docker. This prevents some of the 403 captcha errors.
