### ISSUE TITLE
TZ value

### ISSUE THREAD

**Issue by swiezaczek** [Der-Henning/tgtg#204]
Hello, I just noticed "TZ=Europe/Berlin" in docker file, but this value is missing in config.ini. Is it important value ? Does it have any impact on bot detection? Should I add it to config.ini?

**Comment by Der-Henning** [comment]
Hi @swiezaczek.
Docker containers don't know the timezone of the host system and default to UTC. So all timestamps are displayed as UTC.
One way to change the timezone of a docker container is setting the environment variable TZ.
This configuration only affects the display of dates and times in logs and notifications.

**Comment by swiezaczek** [comment]
Thanks
