### ISSUE TITLE
IFTTT Notification fails

### ISSUE THREAD

**Issue by Bumblebee118** [Der-Henning/tgtg#218]
When using IFTTT, it fails when sending a notification. 

The following error is written to the output (myKey is of course my real key):

`Failed sending IFTTT: myKey: Expecting value: line 1 column 1 (char 0)`

This is my configuration in the docker-compose.yml:

```
- IFTTT=true                                   ## true = enable notifications via IFTTT Webhooks
- IFTTT_EVENT=tgtg_notification                 ## IFTTT Webhooks Event
- IFTTT_KEY=bBWHFknwC2kpo0coOgpo1y                                    ## IFTTT Webhooks Key
- IFTTT_BODY=                                   ## IFTTT json data body
```

Triggering the applet manually via a browser works.

**Comment by Der-Henning** [comment]
Hi @Bumblebee118,

Please comment out the `IFTTT_BODY` option or add a json body like `{"value1": "${{display_name}}", "value2": ${{items_available}}, "value3": "https://share.toogoodtogo.com/item/${{item_id}}"}` (default).
Commenting out will result in the default option.

**Comment by Bumblebee118** [comment]
Thanks a lot. Now it works. I kinda missed that.
