### ISSUE TITLE
SMTP Configuration not working

### ISSUE THREAD

**Issue by FedeGioz** [Der-Henning/tgtg#22]
I've tried both on linux and windows with latest version but i always get that the SMTP configuration is not working, even with your defaults, these are my settings:
[SMTP]
## SMTP Settings / Example for gmail
SMTP = true
enabled = true
Host = smtp.gmail.com
Port = 465
Username = my secondary mail
Password = my secondary mail password
TLS = true 
Sender = my secondary mail
Recipient = my personal mail

**Comment by Der-Henning** [comment]
Hi,
Do you have enabled 2-Step Verifikation for your google account?
In this case you cannot login with your regular google password. Please follow these instructions to create an app password:
[https://support.google.com/mail/answer/185833?hl=en](https://support.google.com/mail/answer/185833?hl=en)

Regards
Henning

**Comment by FedeGioz** [comment]
Thanks, now it works
