### ISSUE TITLE
error saving credentials

### ISSUE THREAD

**Issue by p3t3r** [Der-Henning/tgtg#222]
All of a sudden I'm getting "error saving credentials" errors:
error saving credentials! - [Errno 13] Permission denied: '/tokens/accessToken'
It's occuring on the interval that is provided in the config.

The directory tokens has all the permissions, that doesn't seem to be the problem.
Any idea what to look for?

**Comment by Der-Henning** [comment]
Hi @p3t3r,
the user in the docker container has the uid 1001. Can you double check that the user owns the directory?
Using the provided `docker-compose.yml` and the default docker settings the volume should be placed in `/var/lib/docker/volumes/toogoodtogo_tokens/_data`.

````bash
root@server1:/var/lib/docker/volumes/toogoodtogo_tokens/_data# ls -la
total 20
drwxr-xr-x 2 1001 1001 4096 Mai 20  2022 .
drwx-----x 3 root root 4096 Mai 20  2022 ..
-rw-r--r-- 1 1001 1001  138 Dez 27 22:33 accessToken
-rw-r--r-- 1 1001 1001  138 Dez 27 22:33 refreshToken
-rw-r--r-- 1 1001 1001    7 Dez 27 22:33 userID
````

**Comment by p3t3r** [comment]
I'm running Docker on a Synology NAS, and it had to do with the directory owner. 
I had to change the permissions on the folder from the Synogy interface to allow other users to write.
There is no 1001 user on the Synology docker, so now it's fixed.
The tokens are written in de tokens folder by the way, not in tokens/_data , but it's working.
