### ISSUE TITLE
Unable to find the configfile in Docker

### ISSUE THREAD

**Issue by Nuppers** [Der-Henning/tgtg#223]
Hey,
I'm new to docker.
Where can I find the config file there? I have already installed the image in a new container..

Thanks!!

**Comment by Nuppers** [comment]
Could resolve the issue by myself.
Thanks for the great work!

**Comment by Der-Henning** [comment]
Hi @Nuppers,
I'm glad you could resolve the problem yourself. Feel free to create an issue if you have any further problems or recognize any bugs.

**Comment by flashedk** [comment]
Just out of curiosity - how did you manage to do it?
I can get the project running via docker-compose and editing the .yaml.
But if I pull the image from docker-hub via docker desktop i literally can't find the damn configuration file. So when I want to start it it says you need to provide at least an email.

**Comment by Der-Henning** [comment]
Hi @flashedk.
With docker you don't need a configuration file. You configure the scanner via environment variables.
If you use docker-compose you can set them in the `.yml` file.

**Comment by flashedk** [comment]
Ah got it. Thought I was just stupid. Then docker Compose might be the nicer Version for me
