### ISSUE TITLE
Problem while setting up

### ISSUE THREAD

**Issue by ottoman4290** [Der-Henning/tgtg#225]
Hi,
after installing the current version of tgtg for the first time and Python 3.11, I get the following error and don't know how to fix that:
Jan 02 22:25:55 pi systemd[1]: Started TooGoodToGo.
Jan 02 22:25:55 pi python3[32064]: Traceback (most recent call last):
Jan 02 22:25:55 pi python3[32064]:   File "/home/pi/Desktop/tgtg-1.11.0/src/scanner.py", line 7, in <module>
Jan 02 22:25:55 pi python3[32064]:     from models import Item, Config, Metrics, Cron
Jan 02 22:25:55 pi python3[32064]: ModuleNotFoundError: No module named 'models'
Jan 02 22:25:55 pi systemd[1]: 2good2go.service: Main process exited, code=exited, status=1/FAILURE
Jan 02 22:25:55 pi systemd[1]: 2good2go.service: Failed with result 'exit-code'.

Can you please assist?
Thank you in advance!
Best regards

**Comment by Der-Henning** [comment]
Hi @ottoman4290,
as you run the scanner as a service can you please provide your service configuration file?
If you are using the latest version 1.14.0 you have to call the new `main.py` file.

**Comment by ottoman4290** [comment]
Hi Henning,
I think I have an issue with Python. Therefore, I am installing a fresh copy of Raspbian. I will let you know if this solved the issue.
Thank you for your kind support.

**Comment by ottoman4290** [comment]
After a fresh install, it works like a charm. Thank you anyways!
