### ISSUE TITLE
E-Mail to multiple recipients

### ISSUE THREAD

**Issue by ottoman4290** [Der-Henning/tgtg#227]
Hi Henning,

it's me again. This time I want to send the notification to multiple recipients via e-mail. I tried different syntaxes, but was not successful. Can you please assist?
This works:
Recipient = myMailAddress@mail.com
This doesn't:
Recipient = myMailAddress@mail.com, differentMailAddress@mail.com

How is the exact syntax?

Thanks and best regards

**Comment by HenkTillaart** [comment]
Hello Henning en other people,

Having the same incident as above. Tried different syntaxes like "",',[. 
Mabye you or anyone else have a solution. Thanks everyone.

**Comment by Der-Henning** [comment]
Hi @ottoman4290.
````ini
Recipient = myMailAddress@mail.com, differentMailAddress@mail.com
````
should actually work. I just tried and both mails where send.

**Comment by Der-Henning** [comment]
Ok sorry. I just double checked and confirm this bug. I will fix it as soon as possible and create a new release.

**Comment by Der-Henning** [comment]
The new release v1.14.1 should fix the bug. Any feedback is welcome.

**Comment by HenkTillaart** [comment]
Hello Henning and ottoman4290,

I re-pull the docker image and it works. I just use 2 different emailadress and it will send to both emailadress.
Thanks!
