### ISSUE TITLE
Disregard this one :)

### ISSUE THREAD

**Issue by ihor-chaban** [Der-Henning/tgtg#245]
Disregard this one :)
Can be closed.

**Comment by Der-Henning** [comment]
Hi @ihor-chaban,
This is already the case. The option `ITEM_IDS` is only available due to legacy support and for special use cases. The default behavior is scanning the favorite items set in the provided tgtg account.
If I missunderstood your request please let me know.

**Comment by ihor-chaban** [comment]
Yeah, my bad.
Everything is cool, thanks.
