### ISSUE TITLE
Notifications werden teilweise nicht versandt

### ISSUE THREAD

**Issue by shimanu91** [Der-Henning/tgtg#248]
Hallo, ich habe das Problem, dass häufig durch den Scan festgestellte Änderungen/ Erhöhung der verfügbaren Magic Bags im Logfile festgestellt werden, eine Ausführung einer Send Notifications jedoch oft nicht stattfindet.

**Comment by Der-Henning** [comment]
Hi @shimanu91.
Der Scanner erzeugt nur eine Benachrichtigung, wenn die Anzahl an verfügbaren Tüten von null auf es sind welche verfügbar, sprich > null, springt. Änderungen im Bestand sind aus meiner Sicht nicht interessant.

**Comment by Der-Henning** [comment]
Closing. Feel free to reopen the issue or create a new one if the issue persists or you have any further problems.
