### ISSUE TITLE
get item error! Error 401

### ISSUE THREAD

**Issue by barbotclem** [Der-Henning/tgtg#253]
Hi,

I have this 'get item error!' issue followed by a 401 error while attempting to configure and run the executable service. Afterwards, the service exits. 
It occurs on Mac but also on Docker. Perhaps am I missing something here?
I used the latest on Mac & latest image on Docker. 

Thanks for your work & kind help.

<img width="814" alt="Screenshot 2023-01-25 at 8 32 13 PM" src="https://user-images.githubusercontent.com/32271307/214735884-838b79ec-68e9-4eae-8762-9302b9baa80e.png">

**Comment by Der-Henning** [comment]
Hi @barbotclem.
Which release/docker tag are you using?
Can you please provide your config? With anonymized credentials of course.
Run the scanner in debugging mode (option `DEBUG=true` or argument `main.py -d`) and provide the resulting scanner.log file.

**Comment by barbotclem** [comment]
Please find attached the anonymized scanner.log along with the anonymized config.ini content.
Thanks
[scanner.log](https://github.com/Der-Henning/tgtg/files/10510840/scanner.log)


```
[MAIN]
## true for debug log messages
Debug = true
## Time to wait till next scan in seconds - default 60 seconds
## The Scanner will randomize the wait time by +/- 10%
SleepTime = 120
## Optional Scheduler in cron schedule expression
## Example of cron schedule expression:
## ScheduleCron=* 12-14 * * 1-5     ## = allowed to run from 12:00 to 14:59 on monday to friday
## more help with formatting at https://crontab.guru/#*/1_12-14_*_*_1-5
## The Scanner will not make any requests to the TGTG API in the excluded periods
ScheduleCron = * * * * *
## optional comma seperated list of item ids that should be scanned
ItemIDs =
## Enable to export Metrics for prometheus
Metrics = false
MetricsPort = 8000
## Disable Test Notifications
DisableTests = false

[TGTG]
## TGTG Username / Login EMail
Username = mytgtgmail@mail.com

#### Notifiers
## To enable notifier fill in the needed settings
## and set enabled to true

[SMTP]
## SMTP Settings / Example for gmail
## Subject and Body options are optional.
## Subject and Body options can use variables as described below
## The Body option is interpreted as HTML
enabled = true
Host = smtp.gmail.com
Port = 587
Username = mygmail@mail.com
Password = app password
TLS = true
SSL = false
Sender = mygmail@mail.com
Recipient = mygmail@mail.com
# cron =
# Subject =
# Body =

[PUSHSAFER]
enabled = false
Key =
DeviceID =
# cron =

## The IFTTT Body contains a json string which can use the variables described below for the webhook
## Default Body:
## {"value1": "${{display_name}}", "value2": ${{items_available}}, "value3": "https://share.toogoodtogo.com/item/${{item_id}}"}
[IFTTT]
enabled = false
Event =
# Body =
Key =
# cron =

## To use Telegram notifications you have to create a bot using the @botfather
## If you only provide the token of the bot will use the last chat it reseived a message on
## You can add multiple chat ids as a comma seperated list
## The message body is optional and is interpreted as markdown text
## You can use the same variables as described for the Webhook notifier below
## Example:
## *${{display_name}}*\n*Available*: ${{items_available}}\n*Rating*: ${{rating}}\n*Price*: ${{price}} ${{currency}}\n*Pickup*: ${{pickupdate}}\n*Link*: https://share.toogoodtogo.com/item/${{item_id}}
[TELEGRAM]
enabled = false
token =
chat_ids =
timeout = 60
# cron =
# body =

## WebHook URL and body can contain variables in the form of ${{variable}}
## Available variables: item_id, items_available, display_name, price, currency, pickupdate, description, favorite, rating
## json body example: {"value1": "${{display_name}}", "value2": ${{items_available}}}
## You have to provide "" for strings if needed
[WEBHOOK]
enabled = false
URL =
Method = POST
body =
type = text/plain
timeout = 60
# cron =

```

**Comment by Der-Henning** [comment]
Please try running the scanner with the argument `-t`.
This should perform a login and return your credentials (access token, refresh token and user id).
Does it work?

Does the python script have write access to the `config.ini`?

**Comment by barbotclem** [comment]
Running `./scanner -t` returns the credentials (my email, an access token and a user ID).
I am not running it through Python, just using the Mac terminal or the docker-compose command line.

**Comment by barbotclem** [comment]
That was through Facebook indeed. 
Let me create another tgtg-based account and check if it works.
Thanks!

**Comment by Der-Henning** [comment]
Hi @barbotclem.
Did you succeed?

**Comment by barbotclem** [comment]
Hi, sorry for the delay, I had personal stuff to work on. 
Two things: 

- I used an old 'TooGoodToGo' based account, from France while I am in Canada
- I created a brand 'TooGoodToGo' based account, from Canada while I am in Canada

First option: still the same issue
Second option: it works!

So two options here: my old account is flagged or it is related to the timezone. 
Do you want to dig into this or we close the issue?

Thanks for the help!

**Comment by Der-Henning** [comment]
Hi @barbotclem.
Thank you for your feedback. I'm glad it is working for you now!
As you found a practical solution I would prefer option 2. 😉
Closing.
