### ISSUE TITLE
How to set up Discord webhook ? 

### ISSUE THREAD

**Issue by NuritArmelle** [Der-Henning/tgtg#256]
Hello, firstly thanks for this project it's really amazing !

I tried to configure it to use with a discord Webhook, but i can't make it work ! 
Could you please explain what i can do to ?

Here's my config file and a screenshot of the soft.
![image](https://user-images.githubusercontent.com/11718166/215216549-027b6d45-b2b2-499f-8eb7-7d083fc46340.png)
![image](https://user-images.githubusercontent.com/11718166/215216848-266b6991-0ffa-4407-8c8d-218262d432bb.png)

I tested my webhook and it seems to works just fine.

Thanks again for you work

**Comment by Der-Henning** [comment]
Hi @NuritArmelle,
I didn't use the discord API myself, but I will try to help you.
Based on https://discord.com/developers/docs/resources/webhook#execute-webhook the request type should be `application/json` and the json parameter `content` is required.
I guess your url is based on `/webhooks/{webhook.id}/{webhook.token}`?

**Comment by NuritArmelle** [comment]
Hello, thanks for your quick answer !
Yep i guess it's an url based on that, i generated it directly from Discord in the "Integrations / webhook" option of my server.

Thanks to your documentation, i made it "kinda work" by putting the type to application/json and by putting a "test" content in a json Format.

But i still don't know how to have the content telling me which shop is available (for the moment it just say the string i put in the content parameter)

**Comment by Der-Henning** [comment]
As documented in the [`config.sample.ini`](https://github.com/Der-Henning/tgtg/blob/main/src/config.sample.ini) you can use variables to 'build' the request body.
example:
````ini
body = {"username": "ToGoodToGo Bot", "content": "${{display_name}}: ${{items_available}}, pickup: ${{pickupdate}}"}
````

You can also experiment with the formatting of the content. I guess discord also supports markdown, allowing bold text and new lines. E.g. the body string for the telegram notifier as described in the `config.template.ini`.

**Comment by NuritArmelle** [comment]
Thanks a lot, it works great!
I didn't think I could put parameters like that :)

**Comment by Der-Henning** [comment]
You are welcome!

**Comment by bokkoman** [comment]
> Thanks a lot, it works great! I didn't think I could put parameters like that :)

What is the BODY you used for discord notification? I'm trying to set this up as well.

**Comment by Der-Henning** [comment]
@NuritArmelle Maybe you can shortly summarize what you did to configure discord notifications including how to obtain the tokens and your final config as a template and the links to the relevant resources in the discord documentation.

I will create a wiki page for the other users then.

**Comment by bokkoman** [comment]
> @NuritArmelle Maybe you can shortly summarize what you did to configure discord notifications including how to obtain the tokens and your final config as a template and the links to the relevant resources in the discord documentation.
> 
> I will create a wiki page for the other users then.

That would be awesome.
Now too wait for the docker too work, it can't login. Captcha errors :(

**Comment by NuritArmelle** [comment]
Hello, here is my config.ini if that can help you, it works fine with that :) 
![image](https://user-images.githubusercontent.com/11718166/215849792-e434cf94-b29d-4802-924d-c51e19683581.png)

**Comment by WildCard1** [comment]
Hi.  I struggled a bit with getting WEBHOOK_BODY to work, but this worked for me in docker-compose.yml:

`      - 'WEBHOOK_BODY={"username": "TooGoodToGoBot", "content": "$${{display_name}}: $${{items_available}}, pickup: $${{pickupdate}}"}'
      - WEBHOOK_TYPE=application/json
`
