### ISSUE TITLE
Distribution for Windows - configure scanner.exe output message

### ISSUE THREAD

**Issue by tofik7** [Der-Henning/tgtg#259]
Hi,

Is there any chance to configure the output message (add some more extra informations) for a new bags in a distribution for Windows?

![2023-02-01_211017](https://user-images.githubusercontent.com/82944952/216152970-136c1244-de8e-4d60-b7f8-0d453d2534a9.png)

Have a look above, I would like to see some more data/informations in the main scanner.exe window, simply I would like to configure it to get a message like, HTML  `Body = <b>${{display_name}}</b> - Available: ${{items_available}} Price: ${{price}} ${{currency}} Pickup: ${{pickupdate}}`

I guess  I am not able to achieve it with config.ini and the scanner.exe needs to be edited?

thanks for any advices

**Comment by Der-Henning** [comment]
Hi @tofik7.
I didn't think of the option to just run the scanner and only use the console output to get notified :)
This shouldn't be too hard to implement. I will have a look.
Thank you for your contribution!

**Comment by Der-Henning** [comment]
@tofik7 [this pre Release](https://github.com/Der-Henning/tgtg/suites/10723472737/artifacts/537522839) contains a new simple notifier for the console.

The option `quiet` disables all other log messages.

`config.ini` example:
````ini
[MAIN]
quiet = true

[TGTG]
Username = 

[CONSOLE]
enabled = true
body = ${{display_name}} - new amount: ${{items_available}}
````

**Comment by pershoot** [comment]
Hi.

This is working ok, from initial observation (built from Source; Python 3.9, Linux (AMD64).  With quiet = true + console  = false, log messages (snippet of the tail) from startup:
[2023-02-01 21:08:23][tgtg][main.py:_print_welcome_message:235][INFO]
[2023-02-01 21:08:23][tgtg][main.py:_print_welcome_message:236][INFO] Version 1.14.8
[2023-02-01 21:08:23][tgtg][main.py:_print_welcome_message:237][INFO] ©2022, Henning Merklinger
[2023-02-01 21:08:23][tgtg][main.py:_print_welcome_message:238][INFO] For documentation and support please visit https://github.com/Der-Henning/tgtg
[2023-02-01 21:08:23][tgtg][main.py:_print_welcome_message:239][INFO]

Stops there, with no further entries, as it scans and notifies accordingly.

**Comment by tofik7** [comment]
Hi Henning,
Thank you very much for your effort, it works very well! it wouldn't have crossed my mind you can implement a request within a two hours!

Today I will do some more tests

PS. Just noticed a small cosmetic thing, new messages (updated lines) in the local console are missing "the date + time" values which normally are on the left side in the console. It's not really any kind of issue but maybe it's worth mentioning. Have a look below.
![2023-02-02_091852](https://user-images.githubusercontent.com/82944952/216272697-0fbfc033-2045-4ba8-9ff8-a44970c88253.png)

**Comment by Der-Henning** [comment]
Added `${{scanned_on}}` variable in [b638977](https://github.com/Der-Henning/tgtg/commit/b638977efb706a42c884ad7f48218119e93a8adf). Will be part of the next release.

**Comment by Der-Henning** [comment]
Closing. Thank you for your contribution. Feel free to create a new issue if you have any problems or ideas for improvements.
