### ISSUE TITLE
Telegram notifier; line breaks in body

### ISSUE THREAD

**Issue by pershoot** [Der-Henning/tgtg#263]
Hi.

I can't seem to get line breaks operational for body, in a telegram notifier.  backslash n prints the literal characters and it stays on one line.  I've tried a number of things, in markdown, quoting, etc. and still no go.

Please advise.

Thank you.

**Comment by Der-Henning** [comment]
Hi @pershoot.
I can cofirm your issue. There is a problem with parsing special characters and encoding them again for the notifier APIs. I will make a deep dive into this issue this evening to find a lasting solution.

**Comment by Der-Henning** [comment]
I created a new [pre-Release](https://github.com/Der-Henning/tgtg/suites/10771633832/artifacts/541095617), that hopefully should fix the problems with newline characters.
Any feedback is appreciated.

**Comment by pershoot** [comment]
Hi.  Looks good (built exec. from src; synchro from main).  I'll monitor...

Thank you so much.

**Comment by Der-Henning** [comment]
Included the fix in the latest release [v1.14.10](https://github.com/Der-Henning/tgtg/releases/tag/v1.14.10).

**Comment by Der-Henning** [comment]
Closing. If you have any further problems, feel free to reopen or create a new issue.
