### ISSUE TITLE
Build of 1.3.1 for Linux issue

### ISSUE THREAD

**Issue by harryfear** [Der-Henning/tgtg#27]
The build either thinks it's 1.3.0 while there's an update available (for 1.3.1); or the build actually is 1.3.0 and the build labelled 1.3.1 is in fact a an build (for 1.3.0).

Meanwhile, the build reports "ERROR Configuration Error - Invalid TGTG configuration".

Thanks for all your help as always.

**Comment by Der-Henning** [comment]
Yep. I apparently forgot to set the version to 1.3.1... But the build is working for me and is the correct one.
The account you are using worked on the old versions (previous tgtg API)?
Please try following request to the TGTG API:

`export TGTG_USERNAME=youremail@example.com`
`export TGTG_PASSWORD=yourpassword`
`curl --location --request POST 'https://apptoogoodtogo.com/api/auth/v2/loginByEmail' \`
`--header 'User-Agent: TGTG/21.9.3 Dalvik/2.1.0 (Linux; U; Android 7.0; SM-G935F Build/NRD90M)' \`
`--header 'Accept-Encoding: gzip' \`
`--header 'Content-Type: application/json' \`
`--data-raw "{`
`    \"device_type\": \"ANDROID\",`
`    \"email\": \"${TGTG_USERNAME}\",`
`    \"password\": \"${TGTG_PASSWORD}\"`
`}" \`
`--include --compressed`

The response should be an json object including an access_token as first element.

**Comment by harryfear** [comment]
I either get a 403 HTML Captcha response or I get a blank 404 response with a "set-cookie: datadome" returned?

**Comment by Der-Henning** [comment]
OK. I heard of cases, where tgtg blocked an IP for too many requests. Didn't happen to me though. Can you please try to use a new IP?
You receive a new IP from your ISP by reconnecting your internet connection in your router settings or simply restart your router.

**Comment by harryfear** [comment]
On one host/IP, the CAPTCHA appeared.

But on the others, the 404 response was returned. Not sure if that's 404 user not found or 404 password invalid, but either way, I believe there was no access_token provided.

What is happening with their API and login via email/password? Is there a flow that can be used to provision the Linux app with a logged-in-via-email passwordless access token?

**Comment by Der-Henning** [comment]
It seems TGTG now removed the API endpoint for login by mail and password entirely.
So again, at the moment there is no working solution.

**Comment by FedeGioz** [comment]
this guy fixed it apparently https://github.com/ahivert/tgtg-python/pull/122

**Comment by Der-Henning** [comment]
Fixed in Version 1.4
