### ISSUE TITLE
Add docker-compose.yml example to FAQ

### ISSUE THREAD

**Issue by f321x** [Der-Henning/tgtg#272]
Can you add a example of the docker-compose.yml to your faq?
When trying to set ifttt body up it always throws some formatting error, even when copying the default

- IFTTT_BODY={"value1": "$${{display_name}}", "value2": $${{items_available}}, "value3": "https://share.toogoodtogo.com/item/$${{item_id}}"}
                           ## IFTTT json data body
                           ## Default: {"value1": "$${{display_name}}", "value2": $${{items_available}}, "value3": "https://share.toogoodtogo.com/item/$${{item_id}}"}

like this.
(cant reconstruct rn, the container doesn't even start, smth like expected block end but got ',' instead in line)

**Comment by Der-Henning** [comment]
Hi @f321x.
Did you try surrounding the whole declaration of the variable in `''`?
````yml
- IFTTT=true
- IFTTT_EVENT=tgtg_notification
- IFTTT_KEY=
- 'IFTTT_BODY={"value1": "$${{display_name}}", "value2": $${{items_available}}, "value3": "https://share.toogoodtogo.com/item/$${{item_id}}"'
````

**Comment by f321x** [comment]
Seems to work, thank you very much!

**Comment by Der-Henning** [comment]
Could you please run the scanner in debugging mode (`DEBUG=true`) and provide the relevant logs?

**Comment by f321x** [comment]
x@x:/home/x/tgtg# docker compose logs -f
app_1  | 2023-02-11 21:32:14 INFO     Loaded config from environment variables
app_1  | 2023-02-11 21:32:14 INFO     Debugging mode enabled
app_1  | 2023-02-11 21:32:14 INFO       ____  ___  ____  ___    ____   ___   __   __ _  __ _  ____  ____  
app_1  | 2023-02-11 21:32:14 INFO      (_  _)/ __)(_  _)/ __)  / ___) / __) / _\ (  ( \(  ( \(  __)(  _ \ 
app_1  | 2023-02-11 21:32:14 INFO        )( ( (_ \  )( ( (_ \  \___ \( (__ /    \/    //    / ) _)  )   / 
app_1  | 2023-02-11 21:32:14 INFO       (__) \___/ (__) \___/  (____/ \___)\_/\_/\_)__)\_)__)(____)(__\_) 
app_1  | 2023-02-11 21:32:14 INFO     
app_1  | 2023-02-11 21:32:14 INFO     Version 1.14.10
app_1  | 2023-02-11 21:32:14 INFO     ©2022, Henning Merklinger
app_1  | 2023-02-11 21:32:14 INFO     For documentation and support please visit https://github.com/Der-Henning/tgtg
app_1  | 2023-02-11 21:32:14 INFO     
app_1  | 2023-02-11 21:32:14 DEBUG    Starting new HTTPS connection (1): api.github.com:443
app_1  | 2023-02-11 21:32:14 DEBUG    https://api.github.com:443 "GET /repos/Der-Henning/tgtg/releases/latest HTTP/1.1" 200 1365
app_1  | 2023-02-11 21:32:14 DEBUG    Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x7f3c68a76260>
app_1  | 2023-02-11 21:32:14 DEBUG    Entering: get_me
app_1  | 2023-02-11 21:32:14 DEBUG    Starting new HTTPS connection (1): api.telegram.org
app_1  | 2023-02-11 21:32:14 DEBUG    https://api.telegram.org:443 "POST /bot6250333522:AAEkXQfUkg4rPWrikIFmWL3C-gqiR2By-S4/getMe HTTP/1.1" 200 190
app_1  | 2023-02-11 21:32:14 DEBUG    {'can_join_groups': True, 'supports_inline_queries': False, 'id': 6250333522, 'first_name': 'tgtgbot', 'can_read_all_group_messages': False, 'username': 'tgtgmaxbot', 'is_bot': True}
app_1  | 2023-02-11 21:32:14 DEBUG    Exiting: get_me
app_1  | 2023-02-11 21:32:14 DEBUG    Entering: set_my_commands
app_1  | 2023-02-11 21:32:14 DEBUG    https://api.telegram.org:443 "POST /bot6250333522:AAEkXQfUkg4rPWrikIFmWL3C-gqiR2By-S4/setMyCommands HTTP/1.1" 200 25
app_1  | 2023-02-11 21:32:14 DEBUG    True
app_1  | 2023-02-11 21:32:14 DEBUG    Exiting: set_my_commands
app_1  | 2023-02-11 21:32:14 INFO     Scheduler started
app_1  | 2023-02-11 21:32:14 DEBUG    Looking for jobs to run
app_1  | 2023-02-11 21:32:14 DEBUG    No jobs; waiting until a job is added
app_1  | 2023-02-11 21:32:14 DEBUG    Bot:6250333522:dispatcher - started
app_1  | 2023-02-11 21:32:14 DEBUG    Bot:6250333522:updater - started
app_1  | 2023-02-11 21:32:14 DEBUG    Waiting for Dispatcher and polling to start
app_1  | 2023-02-11 21:32:14 DEBUG    Updater thread started (polling)
app_1  | 2023-02-11 21:32:14 DEBUG    Start network loop retry bootstrap del webhook
app_1  | 2023-02-11 21:32:14 DEBUG    Deleting webhook
app_1  | 2023-02-11 21:32:14 DEBUG    Entering: delete_webhook
app_1  | 2023-02-11 21:32:14 DEBUG    Dispatcher started
app_1  | 2023-02-11 21:32:14 DEBUG    https://api.telegram.org:443 "POST /bot6250333522:AAEkXQfUkg4rPWrikIFmWL3C-gqiR2By-S4/deleteWebhook HTTP/1.1" 200 68
app_1  | 2023-02-11 21:32:14 DEBUG    True
app_1  | 2023-02-11 21:32:14 DEBUG    Exiting: delete_webhook
app_1  | 2023-02-11 21:32:14 DEBUG    Bootstrap done
app_1  | 2023-02-11 21:32:14 DEBUG    Start network loop retry getting Updates
app_1  | 2023-02-11 21:32:14 DEBUG    Entering: get_updates
app_1  | 2023-02-11 21:32:14 INFO     Activated notifiers:
app_1  | 2023-02-11 21:32:14 INFO     - IFTTT: cwwiHhJhJzd9_PluuOM8zq
app_1  | 2023-02-11 21:32:14 INFO     - Telegram: ['-1001877848050']
app_1  | 2023-02-11 21:32:14 INFO     Sending test Notifications ...
app_1  | 2023-02-11 21:32:14 DEBUG    Starting new HTTPS connection (1): play.google.com:443
app_1  | 2023-02-11 21:32:14 DEBUG    https://play.google.com:443 "GET /store/apps/details?id=com.app.tgtg&hl=en&gl=US HTTP/1.1" 200 None
app_1  | 2023-02-11 21:32:14 DEBUG    Using APK version 23.1.11.
app_1  | 2023-02-11 21:32:14 DEBUG    Starting new HTTPS connection (1): apptoogoodtogo.com:443
app_1  | 2023-02-11 21:32:14 DEBUG    https://apptoogoodtogo.com:443 "POST /api/auth/v3/token/refresh HTTP/1.1" 200 None
app_1  | 2023-02-11 21:32:14 DEBUG    https://apptoogoodtogo.com:443 "POST /api/item/v7/ HTTP/1.1" 403 406
app_1  | 2023-02-11 21:32:14 ERROR    (403, b'{"url":"https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAKIWcseEAWcwA1FfUvQ==&cid=4jL7PvYHKm9A3r0_NSRMxs87DX7dwrdPiosdDk~uF6DiRP-iN6C~AyHn0j_KD~A0bN25~Yp4J_xhybLsJB~Lf6MDdvCHBl30ijG8SnDdu73PPhL74Cnabi7iW_jhx2T9&referer=https%3A%2F%2Fapptoogoodtogo.com%2Fapi%2Fitem%2Fv7%2F&hash=1D42C2CA6131C526E09F294FE96F94&t=fe&s=35558&e=00ee94a4319b0aed07c687c8c2da4fce18b49a92296ccdbb5b5a1d551418090d"}')
app_1  | 2023-02-11 21:32:14 DEBUG    https://apptoogoodtogo.com:443 "POST /api/item/v7/ HTTP/1.1" 403 406
app_1  | 2023-02-11 21:32:14 ERROR    TGTG API Error: (403, b'{"url":"https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAKIWcseEAWcwA1FfUvQ==&cid=7Y4eUKj7nVKXBlW5CW5eoC~bVBQ1Q9z-nWYVr9FRMtKg5~214pKyZuGkC-N4lmIDxpitWb3U038z2UXwu0hJnqJIXLod_XHeQM40hxdI-4WvKcYcOletaDI98oqutjuf&referer=https%3A%2F%2Fapptoogoodtogo.com%2Fapi%2Fitem%2Fv7%2F&hash=1D42C2CA6131C526E09F294FE96F94&t=fe&s=35558&e=1ddb1cba6dd053349316dd42a7f0e1ca29d2175b47a55210d82012c9cab64f85"}')
app_1  | 2023-02-11 21:32:14 INFO     Scheduler has been shut down
app_1  | 2023-02-11 21:32:14 DEBUG    Looking for jobs to run
app_1  | 2023-02-11 21:32:14 DEBUG    No jobs; waiting until a job is added
app_1  | 2023-02-11 21:32:14 DEBUG    Stopping Updater and Dispatcher...
app_1  | 2023-02-11 21:32:14 DEBUG    Requesting Dispatcher to stop...
app_1  | 2023-02-11 21:32:15 DEBUG    orderly stopping
app_1  | 2023-02-11 21:32:15 DEBUG    Dispatcher thread stopped
app_1  | 2023-02-11 21:32:15 DEBUG    Bot:6250333522:dispatcher - ended
app_1  | 2023-02-11 21:32:15 DEBUG    Waiting for async thread 1/4 to end
app_1  | 2023-02-11 21:32:15 DEBUG    Closing run_async thread Bot:6250333522:worker:9a8c93c3-1563-4cff-bbc3-574c59e4ae77_0/4
app_1  | 2023-02-11 21:32:15 DEBUG    Closing run_async thread Bot:6250333522:worker:9a8c93c3-1563-4cff-bbc3-574c59e4ae77_1/4
app_1  | 2023-02-11 21:32:15 DEBUG    Closing run_async thread Bot:6250333522:worker:9a8c93c3-1563-4cff-bbc3-574c59e4ae77_2/4
app_1  | 2023-02-11 21:32:15 DEBUG    Closing run_async thread Bot:6250333522:worker:9a8c93c3-1563-4cff-bbc3-574c59e4ae77_3/4
app_1  | 2023-02-11 21:32:15 DEBUG    async thread 1/4 has ended
app_1  | 2023-02-11 21:32:15 DEBUG    Waiting for async thread 2/4 to end
app_1  | 2023-02-11 21:32:15 DEBUG    async thread 2/4 has ended
app_1  | 2023-02-11 21:32:15 DEBUG    Waiting for async thread 3/4 to end
app_1  | 2023-02-11 21:32:15 DEBUG    async thread 3/4 has ended
app_1  | 2023-02-11 21:32:15 DEBUG    Waiting for async thread 4/4 to end
app_1  | 2023-02-11 21:32:15 DEBUG    async thread 4/4 has ended
app_1  | 2023-02-11 21:32:15 DEBUG    Waiting for Bot:6250333522:dispatcher thread to end
app_1  | 2023-02-11 21:32:15 DEBUG    Bot:6250333522:dispatcher thread has ended
app_1  | 2023-02-11 21:32:15 DEBUG    Waiting for Bot:6250333522:updater thread to end
app_1  | 2023-02-11 21:32:24 DEBUG    https://api.telegram.org:443 "POST /bot6250333522:AAEkXQfUkg4rPWrikIFmWL3C-gqiR2By-S4/getUpdates HTTP/1.1" 200 23
app_1  | 2023-02-11 21:32:24 DEBUG    No new updates found.
app_1  | 2023-02-11 21:32:24 DEBUG    []
app_1  | 2023-02-11 21:32:24 DEBUG    Exiting: get_updates
app_1  | 2023-02-11 21:32:24 DEBUG    Bot:6250333522:updater - ended
app_1  | 2023-02-11 21:32:24 DEBUG    Bot:6250333522:updater thread has ended
app_1 exited with code 1


Seems to crash, but it didn't crash when running with debug=false

**Comment by Der-Henning** [comment]
You got the 403 rate limit error here. Please retry.

**Comment by f321x** [comment]
Ok, tried again, this time it didn't crash


app_1  | 2023-02-11 21:36:50 INFO     Debugging mode enabled
app_1  | 2023-02-11 21:36:50 INFO       ____  ___  ____  ___    ____   ___   __   __ _  __ _  ____  ____  
app_1  | 2023-02-11 21:36:50 INFO      (_  _)/ __)(_  _)/ __)  / ___) / __) / _\ (  ( \(  ( \(  __)(  _ \ 
app_1  | 2023-02-11 21:36:50 INFO        )( ( (_ \  )( ( (_ \  \___ \( (__ /    \/    //    / ) _)  )   / 
app_1  | 2023-02-11 21:36:50 INFO       (__) \___/ (__) \___/  (____/ \___)\_/\_/\_)__)\_)__)(____)(__\_) 
app_1  | 2023-02-11 21:36:50 INFO     
app_1  | 2023-02-11 21:36:50 INFO     Version 1.14.10
app_1  | 2023-02-11 21:36:50 INFO     ©2022, Henning Merklinger
app_1  | 2023-02-11 21:36:50 INFO     For documentation and support please visit https://github.com/Der-Henning/tgtg
app_1  | 2023-02-11 21:36:50 INFO     
app_1  | 2023-02-11 21:36:50 DEBUG    Starting new HTTPS connection (1): api.github.com:443
app_1  | 2023-02-11 21:36:50 DEBUG    https://api.github.com:443 "GET /repos/Der-Henning/tgtg/releases/latest HTTP/1.1" 200 1365
app_1  | 2023-02-11 21:36:50 DEBUG    Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x7f5ff3f0a330>
app_1  | 2023-02-11 21:36:50 DEBUG    Entering: get_me
app_1  | 2023-02-11 21:36:50 DEBUG    Starting new HTTPS connection (1): api.telegram.org
app_1  | 2023-02-11 21:36:50 DEBUG    https://api.telegram.org:443 "POST /XXXX4/getMe HTTP/1.1" 200 190
app_1  | 2023-02-11 21:36:50 DEBUG    {'supports_inline_queries': False, 'first_name': 'XXX', 'id': XXX, 'can_join_groups': True, 'is_bot': True, 'can_read_all_group_messages': False, 'username': 'XXX'}
app_1  | 2023-02-11 21:36:50 DEBUG    Exiting: get_me
app_1  | 2023-02-11 21:36:50 DEBUG    Entering: set_my_commands
app_1  | 2023-02-11 21:36:50 DEBUG    https://api.telegram.org:443 "POST /XXXX4/setMyCommands HTTP/1.1" 200 25
app_1  | 2023-02-11 21:36:50 DEBUG    True
app_1  | 2023-02-11 21:36:50 DEBUG    Exiting: set_my_commands
app_1  | 2023-02-11 21:36:50 INFO     Scheduler started
app_1  | 2023-02-11 21:36:50 DEBUG    Looking for jobs to run
app_1  | 2023-02-11 21:36:50 DEBUG    No jobs; waiting until a job is added
app_1  | 2023-02-11 21:36:50 DEBUG    Bot:XXX:dispatcher - started
app_1  | 2023-02-11 21:36:50 DEBUG    Bot:XXX:updater - started
app_1  | 2023-02-11 21:36:50 DEBUG    Waiting for Dispatcher and polling to start
app_1  | 2023-02-11 21:36:50 DEBUG    Updater thread started (polling)
app_1  | 2023-02-11 21:36:50 DEBUG    Start network loop retry bootstrap del webhook
app_1  | 2023-02-11 21:36:50 DEBUG    Deleting webhook
app_1  | 2023-02-11 21:36:50 DEBUG    Entering: delete_webhook
app_1  | 2023-02-11 21:36:50 DEBUG    Dispatcher started
app_1  | 2023-02-11 21:36:50 DEBUG    https://api.telegram.org:443 "POST /XXX/deleteWebhook HTTP/1.1" 200 68
app_1  | 2023-02-11 21:36:50 DEBUG    True
app_1  | 2023-02-11 21:36:50 DEBUG    Exiting: delete_webhook
app_1  | 2023-02-11 21:36:50 DEBUG    Bootstrap done
app_1  | 2023-02-11 21:36:50 DEBUG    Start network loop retry getting Updates
app_1  | 2023-02-11 21:36:50 DEBUG    Entering: get_updates
app_1  | 2023-02-11 21:36:50 INFO     Activated notifiers:
app_1  | 2023-02-11 21:36:50 INFO     - IFTTT: XXX
app_1  | 2023-02-11 21:36:50 INFO     - Telegram: ['-XXX']
app_1  | 2023-02-11 21:36:50 INFO     Sending test Notifications ...
app_1  | 2023-02-11 21:36:50 DEBUG    Starting new HTTPS connection (1): play.google.com:443
app_1  | 2023-02-11 21:36:50 DEBUG    https://play.google.com:443 "GET /store/apps/details?id=com.app.tgtg&hl=en&gl=US HTTP/1.1" 200 None
app_1  | 2023-02-11 21:36:50 DEBUG    Using APK version 23.1.11.
app_1  | 2023-02-11 21:36:50 DEBUG    Starting new HTTPS connection (1): apptoogoodtogo.com:443
app_1  | 2023-02-11 21:36:50 DEBUG    https://apptoogoodtogo.com:443 "POST /api/auth/v3/token/refresh HTTP/1.1" 200 None
app_1  | 2023-02-11 21:36:51 DEBUG    https://apptoogoodtogo.com:443 "POST /api/item/v7/ HTTP/1.1" 200 None
app_1  | 2023-02-11 21:36:51 DEBUG    Sending WebHook Notification
app_1  | 2023-02-11 21:36:51 DEBUG    Webhook url: https://maker.ifttt.com/trigger/tgtg_notification/with/key/cwwiHhJhJzd9_PluuOM8zq
app_1  | 2023-02-11 21:36:51 DEBUG    Webhook body: '{"value1": "gr\u00fcnesKorn", "value2": 0, "value3": "https://share.toogoodtogo.com/item/750320"}'
app_1  | 2023-02-11 21:36:51 DEBUG    Webhook headers: {'Content-Type': 'application/json'}
app_1  | 2023-02-11 21:36:51 DEBUG    Starting new HTTPS connection (1): maker.ifttt.com:443
app_1  | 2023-02-11 21:36:51 DEBUG    https://maker.ifttt.com:443 "POST /trigger/tgtg_notification/with/key/cwwiHhJhJzd9_PluuOM8zq HTTP/1.1" 200 57
app_1  | 2023-02-11 21:36:51 DEBUG    Sending Telegram Notification
app_1  | 2023-02-11 21:36:51 DEBUG    *grünesKorn*
app_1  | *Available*: 0
app_1  | *Price*: 4.00 EUR
app_1  | *Pickup*: -
app_1  | 2023-02-11 21:36:51 DEBUG    Entering: send_message
app_1  | 2023-02-11 21:36:51 DEBUG    Starting new HTTPS connection (2): api.telegram.org
app_1  | 2023-02-11 21:36:51 DEBUG    https://api.telegram.org:443 "POST /XXX:XXXX-XXX-S4/sendMessage HTTP/1.1" 200 445
app_1  | 2023-02-11 21:36:51 DEBUG    {'caption_entities': [], 'channel_chat_created': False, 'group_chat_created': False, 'new_chat_members': [], 'photo': [], 'entities': [{'length': 10, 'offset': 0, 'type': 'bold'}, {'length': 9, 'offset': 11, 'type': 'bold'}, {'length': 5, 'offset': 24, 'type': 'bold'}, {'length': 6, 'offset': 40, 'type': 'bold'}], 'chat': {'title': 'TGTG Bot', 'id': -1001877848050, 'type': 'supergroup'}, 'date': 1676147811, 'delete_chat_photo': False, 'text': 'grünesKorn\nAvailable: 0\nPrice: 4.00 EUR\nPickup: -', 'supergroup_chat_created': False, 'message_id': 9, 'new_chat_photo': [], 'from': {'first_name': 'XXX', 'id': XXX, 'is_bot': True, 'username': 'XXX'}}
app_1  | 2023-02-11 21:36:51 DEBUG    Exiting: send_message
app_1  | 2023-02-11 21:36:51 INFO     Scanner started ...
app_1  | 2023-02-11 21:36:51 DEBUG    https://apptoogoodtogo.com:443 "POST /api/item/v7/ HTTP/1.1" 200 None
app_1  | 2023-02-11 21:36:51 DEBUG    new State: {'750320': 0, '663153': 0}
app_1  | 2023-02-11 21:37:00 DEBUG    https://api.telegram.org:443 "POST /XXX/getUpdates HTTP/1.1" 200 23
app_1  | 2023-02-11 21:37:00 DEBUG    No new updates found.
app_1  | 2023-02-11 21:37:00 DEBUG    []
app_1  | 2023-02-11 21:37:00 DEBUG    Exiting: get_updates
app_1  | 2023-02-11 21:37:00 DEBUG    Entering: get_updates

**Comment by Der-Henning** [comment]
I deleted your logs to hide your private keys. 
The log looks ok though. Is your IFTTT Webhook set up correctly? Did you check in your applet, if it received a request but maybe couldn't parse it or couldn't send a notification to your IFTTT App?

**Comment by f321x** [comment]
It worked fine before with the same credentials, updated the bot version today to the newest one, swiched to docker and transfered the config keys from my old config file i used around ~6 months. But no problem, will use TG then. Thanks for your help!

**Comment by Der-Henning** [comment]
Closing. Feel free to reopen or create a new issue if you have any further problems.
