### ISSUE TITLE
1.15.0; take a long time to stop via systemd

### ISSUE THREAD

**Issue by pershoot** [Der-Henning/tgtg#279]
Hi,

1.15.0 takes quite some time to stop via systemd.

Here is the full trace:
Feb 13 21:01:47 _HOSTNAME_ systemd[1]: Stopping Scanner-TGTG...
Feb 13 21:01:47 _HOSTNAME_ scanner[205125]: Exception ignored in: <function Scanner.__del__ at 0x7f0e88c9d820>
Feb 13 21:01:47 _HOSTNAME_ scanner[205125]: Traceback (most recent call last):
Feb 13 21:01:47 _HOSTNAME_ scanner[205125]:   File "scanner.py", line 173, in __del__
Feb 13 21:01:47 _HOSTNAME_ scanner[205125]:   File "notifiers/notifiers.py", line 61, in stop
Feb 13 21:01:47 _HOSTNAME_ scanner[205125]:   File "main.py", line 269, in _handle_exit_signal
Feb 13 21:01:47 _HOSTNAME_ scanner[205125]: KeyboardInterrupt:
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: scanner_tgtg.service: State 'stop-sigterm' timed out. Killing.
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: scanner_tgtg.service: Killing process 205112 (scanner) with signal SIGKILL.
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: scanner_tgtg.service: Killing process 205125 (scanner) with signal SIGKILL.
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: scanner_tgtg.service: Killing process 205126 (scanner) with signal SIGKILL.
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: scanner_tgtg.service: Killing process 205127 (scanner) with signal SIGKILL.
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: scanner_tgtg.service: Killing process 205128 (n/a) with signal SIGKILL.
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: scanner_tgtg.service: Killing process 205129 (scanner) with signal SIGKILL.
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: scanner_tgtg.service: Killing process 205130 (n/a) with signal SIGKILL.
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: scanner_tgtg.service: Killing process 205131 (n/a) with signal SIGKILL.
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: scanner_tgtg.service: Killing process 205132 (n/a) with signal SIGKILL.
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: scanner_tgtg.service: Main process exited, code=killed, status=9/KILL
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: scanner_tgtg.service: Killing process 205126 (scanner) with signal SIGKILL.
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: scanner_tgtg.service: Failed with result 'timeout'.
Feb 13 21:03:17 _HOSTNAME_ systemd[1]: Stopped Scanner-TGTG.

....
Last change I picked up, prior to building:
de0bbb46127199f30699a4a0a6449c3d8b5dadaf Merge pull request #277 from Der-Henning/dev

....
New dependencies I picked up, prior to building:
humanize-4.6.0-py3-none-any.whl
pyinstaller-5.8.0-py3-none-manylinux2014_x86_64.whl

....
Using Python 3.9.16.

I wanted to let you know.

**Comment by Der-Henning** [comment]
Hi @pershoot.
Thank you for the feedback.
With the latest release, I started catching system signals to shut down all open connections and cleaning up before closing. In this case a SIGTERM signal with a timeout of 90 seconds from systemd.
Could you please tell me which notifiers you use? It would be very helpful if you could run the scanner with the debug option activated and provide the logs of the stopping phase.
I want to figure out which thread/connection doesn't want to get closed...

**Comment by pershoot** [comment]
It took me a few times to reproduce it this go around (before as I was testing it would happen at every shutdown).  This occurrence it stalled slightly (before it was stalling for a bit longer). 

Notifier is Telegram.  IFTTT and SMTP are disabled, but do have a config in place.

[2023-02-14 01:36:07][tgtg][main.py:_handle_exit_signal:268][DEBUG] Received signal 15
[2023-02-14 01:36:07][tgtg][main.py:_run_scanner:203][INFO] Shutting down scanner ...
[2023-02-14 01:36:07][apscheduler.scheduler][base.py:shutdown:198][INFO] Scheduler has been shut down
[2023-02-14 01:36:07][apscheduler.scheduler][base.py:_process_jobs:940][DEBUG] Looking for jobs to run
[2023-02-14 01:36:07][apscheduler.scheduler][base.py:_process_jobs:1016][DEBUG] No jobs; waiting until a job is added
[2023-02-14 01:36:07][telegram.ext.updater][updater.py:stop:823][DEBUG] Stopping Updater and Dispatcher...
[2023-02-14 01:36:07][telegram.ext.updater][updater.py:_stop_dispatcher:848][DEBUG] Requesting Dispatcher to stop...
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:start:479][DEBUG] orderly stopping
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:start:491][DEBUG] Dispatcher thread stopped
[2023-02-14 01:36:07][telegram.ext.updater][updater.py:_thread_wrapper:358][DEBUG] Bot:6063549055:dispatcher - ended
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:stop:511][DEBUG] Waiting for async thread 1/4 to end
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:_pooled:367][DEBUG] Closing run_async thread Bot:6063549055:worker:76f63cd4-ff79-49d2-bfad-23bd8d7ae3f5_2/4
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:_pooled:367][DEBUG] Closing run_async thread Bot:6063549055:worker:76f63cd4-ff79-49d2-bfad-23bd8d7ae3f5_0/4
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:_pooled:367][DEBUG] Closing run_async thread Bot:6063549055:worker:76f63cd4-ff79-49d2-bfad-23bd8d7ae3f5_3/4
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:_pooled:367][DEBUG] Closing run_async thread Bot:6063549055:worker:76f63cd4-ff79-49d2-bfad-23bd8d7ae3f5_1/4
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:stop:514][DEBUG] async thread 1/4 has ended
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:stop:511][DEBUG] Waiting for async thread 2/4 to end
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:stop:514][DEBUG] async thread 2/4 has ended
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:stop:511][DEBUG] Waiting for async thread 3/4 to end
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:stop:514][DEBUG] async thread 3/4 has ended
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:stop:511][DEBUG] Waiting for async thread 4/4 to end
[2023-02-14 01:36:07][telegram.ext.dispatcher][dispatcher.py:stop:514][DEBUG] async thread 4/4 has ended
[2023-02-14 01:36:07][telegram.ext.updater][updater.py:_join_threads:854][DEBUG] Waiting for Bot:6063549055:dispatcher thread to end
[2023-02-14 01:36:07][telegram.ext.updater][updater.py:_join_threads:856][DEBUG] Bot:6063549055:dispatcher thread has ended
[2023-02-14 01:36:07][telegram.ext.updater][updater.py:_join_threads:854][DEBUG] Waiting for Bot:6063549055:updater thread to end
[2023-02-14 01:36:17][telegram.vendor.ptb_urllib3.urllib3.connectionpool][connectionpool.py:_make_request:410][DEBUG] https://api.telegram.org:443 "POST /bot6063549055:AAE13PuMqKToEPv-EL-47_saugKY6fUYDNc/getUpdates HTTP/1.1" 200 23
[2023-02-14 01:36:17][telegram.bot][bot.py:get_updates:3151][DEBUG] No new updates found.
[2023-02-14 01:36:17][telegram.bot][bot.py:decorator:135][DEBUG] []
[2023-02-14 01:36:17][telegram.bot][bot.py:decorator:136][DEBUG] Exiting: get_updates
[2023-02-14 01:36:17][telegram.ext.updater][updater.py:_thread_wrapper:358][DEBUG] Bot:6063549055:updater - ended
[2023-02-14 01:36:17][telegram.ext.updater][updater.py:_join_threads:856][DEBUG] Bot:6063549055:updater thread has ended

**Comment by Der-Henning** [comment]
That's actually how it should look like. Especially the telegram bot needs some time to stop all the threads. 10 seconds seems to be a reasonable time for me. 
As I said systemd sends a SIGTERM to stop the program. Then it waits 90s for it to stop and, if it doesn't, kills it with SIGKILL. When it takes 90s I guess there is something going wrong and the program is stuck at some point.
You can modify the time to kill with  `TimeoutStopSec=` in your systemd service configuration. 30 would be a reasonable value.

**Comment by pershoot** [comment]
Yup.  Thank you.

**Comment by hauk92** [comment]
I have got a similar error mainly (only?) after running the scanner for a long time.

```
Jun 07 19:48:07 server scanner[10769]: 2023-06-07 19:48:07 DEBUG    Received signal 15
Jun 07 19:48:07 server scanner[10769]: 2023-06-07 19:48:07 INFO     Shutting down scanner ...
Jun 07 19:48:07 server systemd[1]: Stopping Too Good To Go scanner...
Jun 07 19:48:07 server scanner[10769]: 2023-06-07 19:48:07 DEBUG    Received signal 15
Jun 07 19:48:07 server scanner[10769]: Exception ignored in: <function Scanner.__del__ at 0x7fdfacf18280>
Jun 07 19:48:07 server scanner[10769]: Traceback (most recent call last):
Jun 07 19:48:07 server scanner[10769]:   File "scanner.py", line 173, in __del__
Jun 07 19:48:07 server scanner[10769]:   File "main.py", line 307, in _handle_exit_signal
Jun 07 19:48:07 server scanner[10769]: KeyboardInterrupt:
Jun 07 19:48:09 server scanner[10769]: 2023-06-07 19:48:09 DEBUG    [https://api.telegram.org:443](https://api.telegram.org/) "POST /botXYZ:XYZ/getUpdates HTTP/1.1" 200 23
Jun 07 19:48:09 server scanner[10769]: 2023-06-07 19:48:09 DEBUG    No new updates found.
Jun 07 19:48:09 server scanner[10769]: 2023-06-07 19:48:09 DEBUG    []
Jun 07 19:48:09 server scanner[10769]: 2023-06-07 19:48:09 DEBUG    Exiting: get_updates
Jun 07 19:48:09 server scanner[10769]: 2023-06-07 19:48:09 DEBUG    Entering: get_updates
Jun 07 19:48:19 server scanner[10769]: 2023-06-07 19:48:19 DEBUG    [https://api.telegram.org:443](https://api.telegram.org/) "POST /botXYZ:XYZ/getUpdates HTTP/1.1" 200 23
Jun 07 19:48:19 server scanner[10769]: 2023-06-07 19:48:19 DEBUG    No new updates found.
Jun 07 19:48:19 server scanner[10769]: 2023-06-07 19:48:19 DEBUG    []
Jun 07 19:48:19 server scanner[10769]: 2023-06-07 19:48:19 DEBUG    Exiting: get_updates
Jun 07 19:48:19 server scanner[10769]: 2023-06-07 19:48:19 DEBUG    Entering: get_updates
Jun 07 19:48:29 server scanner[10769]: 2023-06-07 19:48:29 DEBUG    [https://api.telegram.org:443](https://api.telegram.org/) "POST /botXYZ:XYZ/getUpdates HTTP/1.1" 200 23
Jun 07 19:48:29 server scanner[10769]: 2023-06-07 19:48:29 DEBUG    No new updates found.
Jun 07 19:48:29 server scanner[10769]: 2023-06-07 19:48:29 DEBUG    []
Jun 07 19:48:29 server scanner[10769]: 2023-06-07 19:48:29 DEBUG    Exiting: get_updates
Jun 07 19:48:29 server scanner[10769]: 2023-06-07 19:48:29 DEBUG    Entering: get_updates
Jun 07 19:48:39 server scanner[10769]: 2023-06-07 19:48:39 DEBUG    [https://api.telegram.org:443](https://api.telegram.org/) "POST /botXYZ:XYZ/getUpdates HTTP/1.1" 200 23
Jun 07 19:48:39 server scanner[10769]: 2023-06-07 19:48:39 DEBUG    No new updates found.
Jun 07 19:48:39 server scanner[10769]: 2023-06-07 19:48:39 DEBUG    []
Jun 07 19:48:39 server scanner[10769]: 2023-06-07 19:48:39 DEBUG    Exiting: get_updates
Jun 07 19:48:39 server scanner[10769]: 2023-06-07 19:48:39 DEBUG    Entering: get_updates
Jun 07 19:48:49 server scanner[10769]: 2023-06-07 19:48:49 DEBUG    [https://api.telegram.org:443](https://api.telegram.org/) "POST /botXYZ:XYZ/getUpdates HTTP/1.1" 200 23
Jun 07 19:48:49 server scanner[10769]: 2023-06-07 19:48:49 DEBUG    No new updates found.
Jun 07 19:48:49 server scanner[10769]: 2023-06-07 19:48:49 DEBUG    []
Jun 07 19:48:49 server scanner[10769]: 2023-06-07 19:48:49 DEBUG    Exiting: get_updates
Jun 07 19:48:49 server scanner[10769]: 2023-06-07 19:48:49 DEBUG    Entering: get_updates
Jun 07 19:48:59 server scanner[10769]: 2023-06-07 19:48:59 DEBUG    [https://api.telegram.org:443](https://api.telegram.org/) "POST /botXYZ:XYZ/getUpdates HTTP/1.1" 200 23
Jun 07 19:48:59 server scanner[10769]: 2023-06-07 19:48:59 DEBUG    No new updates found.
Jun 07 19:48:59 server scanner[10769]: 2023-06-07 19:48:59 DEBUG    []
Jun 07 19:48:59 server scanner[10769]: 2023-06-07 19:48:59 DEBUG    Exiting: get_updates
Jun 07 19:48:59 server scanner[10769]: 2023-06-07 19:48:59 DEBUG    Entering: get_updates
Jun 07 19:49:09 server scanner[10769]: 2023-06-07 19:49:09 DEBUG    [https://api.telegram.org:443](https://api.telegram.org/) "POST /botXYZ:XYZ/getUpdates HTTP/1.1" 200 23
Jun 07 19:49:09 server scanner[10769]: 2023-06-07 19:49:09 DEBUG    No new updates found.
Jun 07 19:49:09 server scanner[10769]: 2023-06-07 19:49:09 DEBUG    []
Jun 07 19:49:09 server scanner[10769]: 2023-06-07 19:49:09 DEBUG    Exiting: get_updates
Jun 07 19:49:09 server scanner[10769]: 2023-06-07 19:49:09 DEBUG    Entering: get_updates
Jun 07 19:49:19 server scanner[10769]: 2023-06-07 19:49:19 DEBUG    [https://api.telegram.org:443](https://api.telegram.org/) "POST /botXYZ:XYZ/getUpdates HTTP/1.1" 200 23
Jun 07 19:49:19 server scanner[10769]: 2023-06-07 19:49:19 DEBUG    No new updates found.
Jun 07 19:49:19 server scanner[10769]: 2023-06-07 19:49:19 DEBUG    []
Jun 07 19:49:19 server scanner[10769]: 2023-06-07 19:49:19 DEBUG    Exiting: get_updates
Jun 07 19:49:19 server scanner[10769]: 2023-06-07 19:49:19 DEBUG    Entering: get_updates
Jun 07 19:49:29 server scanner[10769]: 2023-06-07 19:49:29 DEBUG    [https://api.telegram.org:443](https://api.telegram.org/) "POST /botXYZ:XYZ/getUpdates HTTP/1.1" 200 23
Jun 07 19:49:29 server scanner[10769]: 2023-06-07 19:49:29 DEBUG    No new updates found.
Jun 07 19:49:29 server scanner[10769]: 2023-06-07 19:49:29 DEBUG    []
Jun 07 19:49:29 server scanner[10769]: 2023-06-07 19:49:29 DEBUG    Exiting: get_updates
Jun 07 19:49:29 server scanner[10769]: 2023-06-07 19:49:29 DEBUG    Entering: get_updates
Jun 07 19:49:37 server systemd[1]: tgtg.service: State 'stop-sigterm' timed out. Killing.
Jun 07 19:49:37 server systemd[1]: tgtg.service: Killing process 10767 (scanner) with signal SIGKILL.
Jun 07 19:49:37 server systemd[1]: tgtg.service: Killing process 10769 (scanner) with signal SIGKILL.
Jun 07 19:49:37 server systemd[1]: tgtg.service: Killing process 10770 (scanner) with signal SIGKILL.
Jun 07 19:49:37 server systemd[1]: tgtg.service: Killing process 10771 (scanner) with signal SIGKILL.
Jun 07 19:49:37 server systemd[1]: tgtg.service: Killing process 10772 (scanner) with signal SIGKILL.
Jun 07 19:49:37 server systemd[1]: tgtg.service: Killing process 10773 (scanner) with signal SIGKILL.
Jun 07 19:49:37 server systemd[1]: tgtg.service: Killing process 10774 (scanner) with signal SIGKILL.
Jun 07 19:49:37 server systemd[1]: tgtg.service: Killing process 10775 (scanner) with signal SIGKILL.
Jun 07 19:49:37 server systemd[1]: tgtg.service: Killing process 10776 (scanner) with signal SIGKILL.
Jun 07 19:49:37 server systemd[1]: tgtg.service: Main process exited, code=killed, status=9/KILL
Jun 07 19:49:37 server systemd[1]: tgtg.service: Killing process 10773 (scanner) with signal SIGKILL.
Jun 07 19:49:37 server systemd[1]: tgtg.service: Failed with result 'timeout'.
Jun 07 19:49:37 server systemd[1]: Stopped Too Good To Go scanner.
Jun 07 19:49:37 server systemd[1]: tgtg.service: Consumed 22min 4.764s CPU time.
```

Normal shutdowns look like this:
```
Jun 07 20:35:58 server systemd[1]: Stopping Too Good To Go scanner...
Jun 07 20:35:58 server scanner[55541]: 2023-06-07 20:35:58 DEBUG    Received signal 15
Jun 07 20:35:58 server scanner[55541]: 2023-06-07 20:35:58 INFO     Shutting down scanner ...
Jun 07 20:35:58 server scanner[55541]: 2023-06-07 20:35:58 INFO     Scheduler has been shut down
Jun 07 20:35:58 server scanner[55541]: 2023-06-07 20:35:58 DEBUG    Looking for jobs to run
Jun 07 20:35:58 server scanner[55541]: 2023-06-07 20:35:58 DEBUG    No jobs; waiting until a job is added
Jun 07 20:35:58 server scanner[55541]: 2023-06-07 20:35:58 DEBUG    Stopping Updater and Dispatcher...
Jun 07 20:35:58 server scanner[55541]: 2023-06-07 20:35:58 DEBUG    Requesting Dispatcher to stop...
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    orderly stopping
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    Dispatcher thread stopped
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    Bot:XYZ:dispatcher - ended
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    Waiting for async thread 1/4 to end
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    Closing run_async thread Bot:XYZ:worker:XYZ_1/4
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    Closing run_async thread Bot:XYZ:worker:XYZ_2/4
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    Closing run_async thread Bot:XYZ:worker:XYZ_3/4
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    Closing run_async thread Bot:XYZ:worker:XYZ_0/4
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    async thread 1/4 has ended
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    Waiting for async thread 2/4 to end
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    async thread 2/4 has ended
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    Waiting for async thread 3/4 to end
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    async thread 3/4 has ended
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    Waiting for async thread 4/4 to end
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    async thread 4/4 has ended
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    Waiting for Bot:XYZ:dispatcher thread to end
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    Bot:XYZ:dispatcher thread has ended
Jun 07 20:35:59 server scanner[55541]: 2023-06-07 20:35:59 DEBUG    Waiting for Bot:XYZ:updater thread to end
Jun 07 20:36:06 server scanner[55541]: 2023-06-07 20:36:06 DEBUG    [https://api.telegram.org:443](https://api.telegram.org/) "POST /botXYZ:XYZ/getUpdates HTTP/1.1" 200 23
Jun 07 20:36:06 server scanner[55541]: 2023-06-07 20:36:06 DEBUG    No new updates found.
Jun 07 20:36:06 server scanner[55541]: 2023-06-07 20:36:06 DEBUG    []
Jun 07 20:36:06 server scanner[55541]: 2023-06-07 20:36:06 DEBUG    Exiting: get_updates
Jun 07 20:36:06 server scanner[55541]: 2023-06-07 20:36:06 DEBUG    Bot:XYZ:updater - ended
Jun 07 20:36:06 server scanner[55541]: 2023-06-07 20:36:06 DEBUG    Bot:XYZ:updater thread has ended
Jun 07 20:36:06 server systemd[1]: tgtg.service: Deactivated successfully.
Jun 07 20:36:06 server systemd[1]: Stopped Too Good To Go scanner.
Jun 07 20:36:06 server systemd[1]: tgtg.service: Consumed 3.119s CPU time.



Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Received signal 15
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 INFO     Shutting down scanner ...
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 INFO     Scheduler has been shut down
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Looking for jobs to run
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    No jobs; waiting until a job is added
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Stopping Updater and Dispatcher...
Jun 07 20:41:46 server systemd[1]: Stopping Too Good To Go scanner...
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Requesting Dispatcher to stop...
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    orderly stopping
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Dispatcher thread stopped
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Bot:XYZ:dispatcher - ended
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Waiting for async thread 1/4 to end
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Closing run_async thread Bot:XYZ:worker:XYZ_0/4
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Closing run_async thread Bot:XYZ:worker:XYZ_1/4
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Closing run_async thread Bot:XYZ:worker:XYZ_2/4
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Closing run_async thread Bot:XYZ:worker:XYZ_3/4
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    async thread 1/4 has ended
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Waiting for async thread 2/4 to end
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    async thread 2/4 has ended
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Waiting for async thread 3/4 to end
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    async thread 3/4 has ended
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Waiting for async thread 4/4 to end
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    async thread 4/4 has ended
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Waiting for Bot:XYZ:dispatcher thread to end
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Bot:XYZ:dispatcher thread has ended
Jun 07 20:41:46 server scanner[55581]: 2023-06-07 20:41:46 DEBUG    Waiting for Bot:XYZ:updater thread to end
Jun 07 20:41:49 server scanner[55581]: 2023-06-07 20:41:49 DEBUG    [https://api.telegram.org:443](https://api.telegram.org/) "POST /botXYZ:XYZ/getUpdates HTTP/1.1" 200 23
Jun 07 20:41:49 server scanner[55581]: 2023-06-07 20:41:49 DEBUG    No new updates found.
Jun 07 20:41:49 server scanner[55581]: 2023-06-07 20:41:49 DEBUG    []
Jun 07 20:41:49 server scanner[55581]: 2023-06-07 20:41:49 DEBUG    Exiting: get_updates
Jun 07 20:41:49 server scanner[55581]: 2023-06-07 20:41:49 DEBUG    Bot:XYZ:updater - ended
Jun 07 20:41:49 server scanner[55581]: 2023-06-07 20:41:49 DEBUG    Bot:XYZ:updater thread has ended
Jun 07 20:41:49 server systemd[1]: tgtg.service: Deactivated successfully.
Jun 07 20:41:49 server systemd[1]: Stopped Too Good To Go scanner.
Jun 07 20:41:49 server systemd[1]: tgtg.service: Consumed 3.615s CPU time.
```
