### ISSUE TITLE
Webbhook body.encode error

### ISSUE THREAD

**Issue by skrzacikus** [Der-Henning/tgtg#281]
There is an error during sending webhook test notification:
[tgtg][notifiers.py:send:57][ERROR] Failed sending WebHook: https://api.pushover.net/1/messages.json: 'latin-1' codec can't encode characters in position 82-83: Body ('ść') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

There is no problem in version 1.14.8

**Comment by Der-Henning** [comment]
Hi @skrzacikus.
Thank you for the feedback.
The encoding is missing for none JSON data and I will create a fix as soon as possible.

**Comment by Der-Henning** [comment]
The fix is part of the latest [pre-Release](https://github.com/Der-Henning/tgtg/suites/10968083575/artifacts/555471166) and the edge docker images.
Any feedback is appreciated!

**Comment by skrzacikus** [comment]
pre-Release version works fine. Thank you for fix.

**Comment by Der-Henning** [comment]
Created release [v1.15.1](https://github.com/Der-Henning/tgtg/releases/tag/v1.15.1). The binaries and docker images will be available in a couple of minutes.
