### ISSUE TITLE
How to update the docker file

### ISSUE THREAD

**Issue by glennvantorre** [Der-Henning/tgtg#287]
There is No clear instruction in the readme how to update the docker installation

I run a raspberry Pi (dietPi) with the docker image on it from 6 month's ago. Using docker compose.
Is there an easy way to "upgrade" without having to reinstall everything?

**Comment by Der-Henning** [comment]
Hi @glennvantorre.
Just run
```
docker-compose pull
docker-compose up -d
```
This should pull the latest image and update your container accordingly.

**Comment by Der-Henning** [comment]
Added update procedures to the `Readme.md`.
[run-with-docker](https://github.com/Der-Henning/tgtg#run-with-docker)
