### ISSUE TITLE
TGTG Login Not Working

### ISSUE THREAD

**Issue by FedeGioz** [Der-Henning/tgtg#29]
I was logged in and the scanner was working, when i logged out to try a thing the token refreshed and with the same credentials i wasn't able to log in, i get TGTG configuration error, i also noticed that they don't use the password anymore, just the emailed code so i think it needs to be reworked, error: https://paste.ofcode.org/3w2ymv97sT6BfbqVDqkji9

**Comment by Der-Henning** [comment]
copy of #27 
TGTG removed the API endpoint to login via mail and password.
