### ISSUE TITLE
Only have one item listed, in my telegram notifier

### ISSUE THREAD

**Issue by Reems59** [Der-Henning/tgtg#290]
Hello, 
I've just tested this project and it's really nice! and I don't know why I only have one of my favorite item of TGTG listed in my telegram notifier. I didn't override the body parameter. I just added the token and the chat_ids. 
Can anyone help me solve my problem? 

Thank you in advance,

**Comment by Der-Henning** [comment]
Hi @Reems59.
The scanner sends one notification for every item that gets available. So you only receive a notification as the available amount of one of your favorites raises from zero to something.
Does this answer your question?

**Comment by Reems59** [comment]
Thank you for your answer !
Ok, so it's normal to get,  when I start the scanner and not all the items are available, an item that has zero?

**Comment by Der-Henning** [comment]
At the startup the scanner sends a test notification by default, so you can verify that everything is working as intended. You can disable this test by setting `DisableTests = False`.

**Comment by Reems59** [comment]
Perfect ! Thank's a lot !
