### ISSUE TITLE
WARNING Too many captcha Errors! Spleeping for 10 minutes..

### ISSUE THREAD

**Issue by bennair** [Der-Henning/tgtg#293]
Hi Henning & else,

I am getting the mentioned error message:
"WARNING Too many captcha Errors! Spleeping for 10 minutes.."

Any way to fix that? I'm running the code via docker on a vServer.

Thanks,
Ben

**Comment by Der-Henning** [comment]
Hi @bennair.
Sorry, I reply so late. Did you start the scanner the first time or did it work before?
Running on a VPS might cause issues as TGTG seems to block the IP ranges of some VPS providers.

**Comment by bennair** [comment]
Hi @Der-Henning,
it did work before. I did probably too many requests. Any tips here on how many items or which frequency the scanner should scan?
Thanks, Ben

**Comment by markvdb** [comment]
FYI, I recently ran into this issue too. I've adjusted to a 60 second polling frequency and  the polling times to 9 am - 9pm. Let's hope that helps!

**Comment by oryinchan** [comment]
> 30 seconds

Will 30 seconds sleep time give u ban quick? I'm aiming to run just for specific store for about 1 hour.
