### ISSUE TITLE
Hi; Cannot start 1.16.0 after building executable from source.

### ISSUE THREAD

**Issue by pershoot** [Der-Henning/tgtg#299]
Hi.

1.16.0 cannot start after building 'executable' from source.  I picked up the latest source (main branch) and ran 'install' to pick up the latest packages.

Please advise.

...

Full stack:
Mar 10 12:28:43 HOSTNAME systemd[1]: Started Scanner-TGTG.
Mar 10 12:28:43 HOSTNAME scanner[59980]: Traceback (most recent call last):
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "main.py", line 19, in <module>
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "scanner.py", line 9, in <module>
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "notifiers/__init__.py", line 2, in <module>
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "notifiers/notifiers.py", line 5, in <module>
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "notifiers/apprise.py", line 3, in <module>
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "apprise/__init__.py", line 58, in <module>
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "apprise/plugins/__init__.py", line 41, in <module>
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "apprise/plugins/NotifyBase.py", line 45, in <module>
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "apprise/AppriseAttachment.py", line 33, in <module>
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "apprise/attachment/__init__.py", line 122, in <module>
Mar 10 12:28:43 HOSTNAME scanner[59980]:   File "apprise/attachment/__init__.py", line 53, in __load_matrix
Mar 10 12:28:43 HOSTNAME scanner[59980]: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIP77amy/appris>
Mar 10 12:28:43 HOSTNAME scanner[59980]: [59980] Failed to execute script 'main' due to unhandled exception!
Mar 10 12:28:43 HOSTNAME systemd[1]: scanner_tgtg.service: Main process exited, code=exited, status=1/FAILURE
Mar 10 12:28:43 HOSTNAME systemd[1]: scanner_tgtg.service: Failed with result 'exit-code'.
Mar 10 12:28:44 HOSTNAME systemd[1]: scanner_tgtg.service: Scheduled restart job, restart counter is at 5.
Mar 10 12:28:44 HOSTNAME systemd[1]: Stopped Scanner-TGTG.
Mar 10 12:28:44 HOSTNAME systemd[1]: scanner_tgtg.service: Start request repeated too quickly.
Mar 10 12:28:44 HOSTNAME systemd[1]: scanner_tgtg.service: Failed with result 'exit-code'.
Mar 10 12:28:44 HOSTNAME systemd[1]: Failed to start Scanner-TGTG.

...

Thank you.

**Comment by Der-Henning** [comment]
Hi @pershoot.
Thank you for the bug report. Bugfix is incoming. I will release v1.16.1 as soon as possible.

**Comment by Der-Henning** [comment]
Release 1.16.1 is available and should fix this problem. Any feedback is appreciated. :)

**Comment by pershoot** [comment]
Hi.

Thank you.

Looks good; I'll monitor.

Mar 10 17:09:37 HOSTNAME systemd[1]: Started Scanner-TGTG.
Mar 10 17:09:38 HOSTNAME scanner[64403]: 2023-03-10 17:09:38 INFO     Loaded config from /opt/scanner_tgtg/config.ini
Mar 10 17:09:38 HOSTNAME scanner[64403]: 2023-03-10 17:09:38 INFO       ____  ___  ____  ___    ____   ___   __   __ _  >
Mar 10 17:09:38 HOSTNAME scanner[64403]: 2023-03-10 17:09:38 INFO      (_  _)/ __)(_  _)/ __)  / ___) / __) / _\ (  ( \(>
Mar 10 17:09:38 HOSTNAME scanner[64403]: 2023-03-10 17:09:38 INFO        )( ( (_ \  )( ( (_ \  \___ \( (__ /    \/    //>
Mar 10 17:09:38 HOSTNAME scanner[64403]: 2023-03-10 17:09:38 INFO       (__) \___/ (__) \___/  (____/ \___)\_/\_/\_)__)\>
Mar 10 17:09:38 HOSTNAME scanner[64403]: 2023-03-10 17:09:38 INFO
Mar 10 17:09:38 HOSTNAME scanner[64403]: 2023-03-10 17:09:38 INFO     Version 1.16.1
Mar 10 17:09:38 HOSTNAME scanner[64403]: 2023-03-10 17:09:38 INFO     ©2022, Henning Merklinger
Mar 10 17:09:38 HOSTNAME scanner[64403]: 2023-03-10 17:09:38 INFO     For documentation and support please visit https:/>
Mar 10 17:09:38 HOSTNAME scanner[64403]: 2023-03-10 17:09:38 INFO

**Comment by Der-Henning** [comment]
Closing. Feel free to reopen or create a new issue if the problem persists.
