### ISSUE TITLE
Docker Synology

### ISSUE THREAD

**Issue by mbaruzzo** [Der-Henning/tgtg#310]
Hello!
Thanks a lot for this, I successfully run the exe and configured the notifications with Telegram.
Now I would like to install it on my Synology with Docker but I am not able to.
I tried to install the container and to run it but no configuration file is created automatically. In the log file indeed says that no notifiers and log in details are not present.
I am not an expert of Docker but I was wondering if you can provide more info than the one I can find in the documentation regarding docker and synology.

Thanks.

**Comment by mbaruzzo** [comment]
Hi! I got it and it seems to be working!
However, in the log of the docker I find an error "ERROR SAVING CREDENTIALS! - [ERRNO 13]"
Can you perhaps know how to fix it?

Thanks again!

**Comment by Der-Henning** [comment]
This error occurs when the scanner has no write access to the `tokens` volume. The scanner writes as a user with the uid 1000. 
DId you create a named volume for the volume `/tokens`? Can you provide your configuration? Screenshots?

**Comment by mbaruzzo** [comment]
@Der-Henning I solved the issue by following the advice I found here:

https://forums.unraid.net/topic/136367-error-saving-credentials-errno-13-permission-denied-tokensaccesstoken/

In my case I accessed via SSH on Synology with root and then entered the following command.

chown 1001:1001 /volume1/docker/tgtg/tokens

Thanks!

**Comment by Der-Henning** [comment]
Thank you for the feedback! I will create a note in the Wiki to help others having this problem.
