### ISSUE TITLE
How to set up a notifier?

### ISSUE THREAD

**Issue by Cohaven** [Der-Henning/tgtg#316]
I see that this project supports all kinds of notifiers, and the config.ini has descriptions and examples of configs. however, none of the documentation that I could find in this project point to any explanation on how to set them up and where to get all the necessary config values. This is my first time setting up this kind of notifier, so some guidance would be appreciated. I'm sure there are other users who would benefit from this guidance as well. 

Which notifier would you recommend for a simple setup where I get notifications by email or text? Which guide should I follow to set that up?

**Comment by Cohaven** [comment]
The notifier works great. However, I wonder if you have any recommendations for running your project in the cloud, so that I don't have to keep my PC on all the time. Is it too complex for Lambda/Cloud Function free tier deployment?

**Comment by Der-Henning** [comment]
Of cause, you can try to use a VPS but it seems that TGTG blocks the IP ranges of many cloud providers.
For 24/7 notifications I recommend running it on an existing NAS like Synology or a Raspberry Pi.

**Comment by immortalys** [comment]
Oracle`s free-tier VPS works like a charm

**Comment by Der-Henning** [comment]
@immortalys Thank you for this insight.
Closing as the issue seems to be resolved. Feel free to reopen or create a new issue if you have any further problems.
