### ISSUE TITLE
Method

### ISSUE THREAD

**Issue by HurrayForScience** [Der-Henning/tgtg#319]
Hi, this is not an issue, but I am learning Python and I wanted to see if I could build something similar to this as a learning project. I was looking at finding ways to retrieve data/metadata from Too Good To Go, and I could not find any publicly shared API methods to do so. Were you able to find documentation for APIs, or does this use another method?

Thanks!

**Comment by HurrayForScience** [comment]
Ah, got it. It must've been a bit of work to get these requests figured out! I've believe I've gotten everything working on this application through Docker on my Synology NAS. 

The test notification came through. However, I am still waiting for an actual notification to be sent to me. I think it's just because Too Good To Go is relatively new in my area, and there aren't that many  participating restaurants yet. The logs have not updated from "Scanner Started" about few hours ago. I want to make sure. The notification triggers when a restaurant I have marked as a favorite has new inventory?

**Comment by Der-Henning** [comment]
You are welcome. 
Feel free to share your experiences. I am afraid you will have problems though, as TGTG seems to block the IP ranges of many cloud providers.

**Comment by HurrayForScience** [comment]
Interesting. I suppose I should see if I can run even the container on ECS to see if that will work.
