### ISSUE TITLE
[Feature request] Add bag URL to message

### ISSUE THREAD

**Issue by KaKi87** [Der-Henning/tgtg#320]
Hello,

The bag page of the TGTG app has a share button, pointing to an URL like `share.toogoodtogo.com/item/<id>`.

Clicking that URL from any other app instantly opens said page, which therefore would be particularly useful in the Telegram notification message.

Thanks

**Comment by Wolbaal** [comment]
Great idea, if possible....

**Comment by Der-Henning** [comment]
Hi @KaKi87 and @Wolbaal.
This feature is already included as you can use the variable `${{item_id}}` to build the url.
As described in the [Wiki](https://github.com/Der-Henning/tgtg/wiki/Configuration#basic-configuration) many notifiers already include this as a default value.
The correct string is `https://share.toogoodtogo.com/item/${{item_id}}`.
With ea519fad2b687957fbf6bae9899cbd11173e81d7 I implemented the variable `${{link}}` that returns the full url for convenience. It will be included in the next release.

**Comment by KaKi87** [comment]
Awesome, thanks !

**Comment by Wolbaal** [comment]
Hi,

Thanks for quick reply! So do I understand clear that it will be automatically in the next version also for telegram?

**Comment by Der-Henning** [comment]
@Wolbaal The variable `${{link}}` will be available for all notifiers, that allow variables. It is only shorthand for `https://share.toogoodtogo.com/item/${{item_id}}`.
To add the link to your telegram messages set the `Body` parameter in your telegram configuration.
E.g.:
````ini
Body=*${{display_name}}* \n*Available*: ${{items_available}}\n*Price*: ${{price}} ${{currency}}\n*Pickup*: ${{pickupdate}}\nhttps://share.toogoodtogo.com/item/${{item_id}}
````
This is the default Body appended by the share link.
