### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Wolbaal** [Der-Henning/tgtg#324]
Hi, after unplug the rpi now after restart the Tgtg won't connect. The rpi luckily has connection (the newer version of portainer is showing up). Any idea what is going wrong?

**Comment by Der-Henning** [comment]
Hi @Wolbaal.
Can you provide some logs showing your problem? And please activate debug mode.

**Comment by Wolbaal** [comment]
Hi, tried this morning some things and also stopped the stack and started. This was solving the issues 😅 anyway thanks for reply! Regards

**Comment by Wolbaal** [comment]
Solved 😀
