### ISSUE TITLE
 Issue with sending notifications from tgtg

### ISSUE THREAD

**Issue by ghost** [Der-Henning/tgtg#327]
![zczcxzx](https://user-images.githubusercontent.com/105560681/234283864-2ae63b8d-594e-49f1-8bd8-089d6e6461bf.jpg)
![sfdsfsdfsd](https://user-images.githubusercontent.com/105560681/234287707-48596f75-808d-4800-9122-a637e2c87474.png)
error as shown in the picture

**Comment by Der-Henning** [comment]
Hi.
Did you receive the notification sent at 15:12:32?
The error you see indicates that you have connection problems with the telegram API. This doesn't harm the basic functionality though.

**Comment by dan271991** [comment]
I received a notification on Telegram.

**Comment by Der-Henning** [comment]
As the telegram updater errors don't do any harm but can be very annoying and the error messages could be misunderstood, they will be only visible in debug mode. 9be0bfdb05a3e79d3ff7d8602233a29409a482a1
This update will be part of the next release.
