### ISSUE TITLE
Telegram Notifier - issue with code

### ISSUE THREAD

**Issue by JissXL** [Der-Henning/tgtg#338]
Hi,

I created a bot using @BotFather obtaining my unique identifier (Token)

Configuration is like this (example)
`[TELEGRAM]`
`Enabled = true`
`Token = `6753805754:AAFHlZjFnwkeLdYvCU5R0y5w9-v3XxuRFi4``

Starting the scanner.exe I get following message:

`2023-05-09 16:24:00 WARNING  You enabled the Telegram notifications without providing a chat id!`
`2023-05-09 16:24:00 WARNING  Send 7477 to the bot in your desired chat.`
`2023-05-09 16:24:00 WARNING  Waiting for code `...``

It is stuck in this state. No message is received in the chat with my bot.
Any suggestions?

**Comment by pershoot** [comment]
@JissXL Hi.  You did not provide 'chat_ids =' to complete the configuration.  As per the description, it will use the last chat id the bot received a message on.  In this scenario, initiate a chat with the bot as relayed by the WARNING.  Alternatively, if you want to find your chat_id: https://api.telegram.org/bot___:____/getUpdates (replace ___:____ with the token) after initiating a chat with the bot.

**Comment by JissXL** [comment]
> @JissXL Hi. You did not provide 'chat_ids =' to complete the configuration. As per the description, it will use the last chat id the bot received a message on. In this scenario, initiate a chat, accordingly, with the bot as relayed by the WARNING. Alternatively, if you want to find your chat_id: https://api.telegram.org/botAAA:BBBB/getUpdates (replace AAA:BBBB with the token) after initiating a chat with the bot.

Thank you very much :-) It helped me a lot and I now can run the app with telegram notifcations. Great!!! :-)

**Comment by Der-Henning** [comment]
Closing. Feel free to reopen if the problem persists or to create a new issue.
