### ISSUE TITLE
[Feature request] Make docker-compose app start at boot

### ISSUE THREAD

**Issue by KaKi87** [Der-Henning/tgtg#339]
Hello,

I would like to suggest adding `restart: always` to the `docker-compose` file so that the app starts automatically at boot by default.

Thanks

**Comment by Der-Henning** [comment]
Hi @KaKi87,
the provided `docker-compose.yml` is more of an example to show the possible configuration options or the image. You should modify it according to your personal needs. The docker configuration is out of this project's scope, but I will add the link to the [docker-compose specifications](https://docs.docker.com/compose/compose-file/) somewhere.
