### ISSUE TITLE
ModuleNotFoundError: No module named '_ctypes'

### ISSUE THREAD

**Issue by Tqnsls** [Der-Henning/tgtg#350]
Hi Henning,

after the update I can restart the scanner.
I even created a new python3.9 env to test the behavior from scratch.

Hardware: Raspberry Pi 4
OS: Raspbian GNU/Linux 10 (buster)"
`python3.9 -V`: "Python 3.9.16"

After running `python3.9 src/main.py` I get these errors.

![image](https://github.com/Der-Henning/tgtg/assets/67681686/a2ec1d84-c06e-4251-bd31-bed5b6d82212)

Do you see what could be the error?
Seems ctypes was introduced in this update.

`pipe3.9 list`
![image](https://github.com/Der-Henning/tgtg/assets/67681686/f51e235f-9d3c-4528-9401-5e1e1dec582a)

**Comment by Der-Henning** [comment]
Hi @Tqnsls.
You might need to install `libffi-dev`.
```bash
sudo apt-get update
sudo apt-get install libffi-dev
```

**Comment by Tqnsls** [comment]
You were right!
`libffi-dev` was not even installed and I had to compile my own python3.9 ages ago for the scanner. Here i did not add `libffi-dev`..

Solved it for me:
`sudo apt-get update
sudo apt-get install libffi-devconfigure --with-system-ffi
make`

Would it make sense to add that `libffi-dev` to the requirements of "Run from source"?

**Comment by Der-Henning** [comment]
Thank you for the feedback. 
I will add a note to the readme.
