### ISSUE TITLE
Can't parse entities

### ISSUE THREAD

**Issue by Marcel-NL1963** [Der-Henning/tgtg#351]
After installing update 1.16.3 on my Synology NAS I got an error message: Telegram Error: Can't parse entities: can't find end of entity starting at byte offset 161.
Can you help me solve this?
![2023-05-31_12-58-18](https://github.com/Der-Henning/tgtg/assets/122172339/8b82e508-41d8-4c24-a806-d2f5b5ea172b)

Thanks in advance.

**Comment by Der-Henning** [comment]
Hi @Marcel-NL1963.
From which version did you upgrade?
The error might be caused by an invalid message body. Could you please provide your config for the telegram notifier? Without the tokens of cause.

**Comment by Marcel-NL1963** [comment]
I updated from 1.16.2 to 1.16.3. I did this by stopping the old version and installing the new by duplicating the settings.

![2023-05-31_13-06-37](https://github.com/Der-Henning/tgtg/assets/122172339/e4c2138a-d16f-4d52-b826-33f638eb38c8)

**Comment by Der-Henning** [comment]
Could you please provide the whole value for the `TELEGRAM_BODY`?
Did you receive this error for the first time? This error could be caused by markdown characters in the `display_name` of the scanned items. I will fix this problem.
Could you please provide the IDs of the items you are watching so I could test the solution? 
You see the IDs when you run the scanner with `DEBUG=true`.

**Comment by Marcel-NL1963** [comment]
#- TELEGRAM_BODY=*${{display_name}}* \n*Beschikbaar*: ${{items_available}}\n*Bedrag*: ${{price}} ${{currency}}\n*Ophalen*: ${{pickupdate}}
I found out that something was wrong because I wasn't receiving almost any notifications.

Sorry for my lack of knowledge, but I don't know where to put debug=true in Synology. So I've done this in the Windows version, it comes with a lot of information, but I cannot see any ID's.

**Comment by Der-Henning** [comment]
There is a message like
```
DEBUG    new State: {'392605': 3, ...
```
These are the item IDs with the currently available number of bags.

**Comment by Marcel-NL1963** [comment]
![afbeelding](https://github.com/Der-Henning/tgtg/assets/122172339/c7089812-2fbc-4443-9b08-68bd86c7a341)

**Comment by Der-Henning** [comment]
On startup, the scanner sends a test notification so you can see if everything is set up correctly. You can disable this behavior with `DisableTests = True`.

**Comment by Marcel-NL1963** [comment]
Have you found anything that causes this error message?

**Comment by Marcel-NL1963** [comment]
I've just found out that when there's one magix box available, I get a notification. When there's two or more boxes available the error message appears and no notifications at all.

**Comment by Marcel-NL1963** [comment]
Sorry for my ignorance, but I just wait for the next release, or can I do something now to see if the bug is solved?

**Comment by Der-Henning** [comment]
As you are using the docker image with your Synology you could use the `derhenning/tgtg:edge` image instead of the `latest` or `1.16.3` tag.

**Comment by pershoot** [comment]
@Der-Henning Hi.  I built against latest in main with this ver., and receive this in the Telegram notify when using 'link' in body.

[2023-06-01 10:55:53][tgtg][telegram.py:_send_message:134][ERROR] Telegram Error: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'

Body item:
*Link*: https://share.toogoodtogo.com/item/${{item_id}}

Thank you.

**Comment by Marcel-NL1963** [comment]
> As you are using the docker image with your Synology you could use the `derhenning/tgtg:edge` image instead of the `latest` or `1.16.3` tag.

I've just installed the edge image, there are no boxes in my fafourites right now, so I jiust wait for that. In the meantime no error messages ;)

**Comment by pershoot** [comment]
> Hi @pershoot. Yes, the latest code uses the `Markdown_V2` parser of the Telegram API. This parser requires all markdown-related characters that should not be used as markdown commands to be escaped with a preceding `\`. The characters are `_`, `*`, `[`, `]`, `(`, `)`, `~`, `` ` ``, `>`, `#`, `+`, `-`, `=`, `|`, `{`, `}`, `.`, `!`.
> 
> So your body should be: `*Link*: https://share\.toogoodtogo\.com/item/${{item_id}}`
> 
> To include the link in your message you could also use the variable `*Link*: ${{link}}`.
> 
> Thank you for pointing out this issue, as this is a breaking change. I will make a special note for this.

Ahh, yup.  Thank you.
