### ISSUE TITLE
error after installation of new version

### ISSUE THREAD

**Issue by elgolmon** [Der-Henning/tgtg#352]
Hello,

I cannot run it anymore after update. I don't understand where it is coming from.
I'm running it on a raspberry pi with raspbian. 
I filled in the config.ini file, apart from TGTG token.

```shell
pi@raspberrypi:~/n1/tgtg $ python src/main.py
Traceback (most recent call last):
  File "/home/pi/n1/tgtg/src/main.py", line 341, in <module>
    main()
  File "/home/pi/n1/tgtg/src/main.py", line 137, in main
    file_handler = logging.FileHandler(log_file, mode="w", encoding='utf-8')
  File "/usr/lib/python3.9/logging/__init__.py", line 1142, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/home/pi/n1/tgtg/src/scanner.log'
``` 

I also performed an update, without any improvement.

**Comment by Der-Henning** [comment]
Hi @elgolmon.
There seems to be a problem with your file permissions.
Quick fix: delete the `scanner.log` file.
You might need to do so with root privileges `sudo rm /home/pi/n1/tgtg/src/scanner.log`.

The `scanner.log` file is created by the scanner during running and created with the user that runs the scanner. Did you run the scanner as root before? This might be the case when you run it as a service or with the `sudo` command.
In this case, the regular user `pi` cannot overwrite the file.
To check the current file permissions cd into the directory and run `ls -la`.

**Comment by elgolmon** [comment]
Hello @Der-Henning 
Thanks for your help !

```shell
pi@raspberrypi:~/n1/tgtg/src $ sudo python main.py
Traceback (most recent call last):
  File "/home/pi/n1/tgtg/src/main.py", line 11, in <module>
    import colorlog
ModuleNotFoundError: No module named 'colorlog'
``` 

In case, I cheked colorlog module, it's already installed :  
```shell
pi@raspberrypi:~/n1/tgtg/src $ pip install colorlog
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: colorlog in /home/pi/.local/lib/python3.9/site-packages (6.7.0)
``` 

Before new installation, I used to run it without sudo

**Comment by Der-Henning** [comment]
You shouldn't run the scanner as root. If you really want to do so you have to install the packages as root too. 
Did you try to remove the `scanner.log` file?

**Comment by elgolmon** [comment]
Thanks for your help again, it's working like a charm when I installed packages as root. I'm still learning :-)
