### ISSUE TITLE
Volume (VOLUME) is banned in Dockerfiles?

### ISSUE THREAD

**Issue by danielkoller** [Der-Henning/tgtg#360]
Hi @Der-Henning - thanks for the great project! I wanted to host the application on Railway for 24/7 monitoring, but I get the following error while building it -> `Volume (VOLUME) is banned in Dockerfiles`.

Any idea, how to solve this issue? Thanks and keep up the great work! 

<img width="825" alt="Bildschirmfoto 2023-06-04 um 13 28 58" src="https://github.com/Der-Henning/tgtg/assets/15102417/4f08f850-a587-4139-8ab1-e23395245d90">

**Comment by Der-Henning** [comment]
Hi, @danielkoller.
Sorry, I don't use Railway. It seems you try to deploy on Railway and build the docker image in the process. Maybe try to use the pre-build images from docker hub and deploy them directly?
As I don't know the deployment process of Railway I cannot help you here.

**Comment by danielkoller** [comment]
I will try that. Thanks again for the support and great application!

**Comment by danielkoller** [comment]
I went another route and deployed it on fly.io. Worked like a charme and they have a great free tier. Thanks, I will close this issue now.
