### ISSUE TITLE
scanner stops working

### ISSUE THREAD

**Issue by RickMartens23** [Der-Henning/tgtg#363]
Hi, 

When i start the scanner (i have edited the config) it starts and stops. See the log. Is it someting i did wrong in the config?

Grz. Rick
[scanner1.log](https://github.com/Der-Henning/tgtg/files/11654382/scanner1.log)

**Comment by Der-Henning** [comment]
Hi, @RickMartens23.
There seems to be a problem with your configuration file. Obviously, the error message is not very helpful. I would like to find out the cause of this error to improve this.
Could you provide your configuration file, so I can have a look? Please ensure not to share sensitive information like API keys and passwords.

**Comment by RickMartens23** [comment]
thanks a lot, it was the SMTP notifier. I have to update these settings. Got it running now!
