### ISSUE TITLE
scanner/cron: Warning regarding improper params

### ISSUE THREAD

**Issue by punfil** [Der-Henning/tgtg#366]
Hi!

I am a beginner here, but noticed probably unexpected behaviour when using SLEEP_TIME in docker config file.

First, no matter the setting, the program always outputs `Every minute` if cron settings are somehow modified, which confused me:
```python
if self.cron.cron != "* * * * *":
            log.info("Active on schedule: %s",
                     self.cron.get_description(self.config.locale))
```
Added a small info log:
```python
if self.config.sleep_time != 60:
            log.info("Cron time setting override, scan every: %s seconds",
                     self.config.sleep_time)
```

Secondly, when mixing cron minutes setting with SLEEP_TIME unexpected behaviour is observed. Let's suppose cron = "*/2 * * * *" and SLEEP_TIME = 90 (judging by my understanding of wiki it's a valid configuration):
Output of a simple test:
```bash
Cron override active: Every 90 seconds.
Time of execution: 14:26:14
Scanner disabled by cron schedule.
Scanner reenabled by cron schedule.
Time of execution: 14:30:43
```
I guess that is not a desired behaviour and to prevent from such situation added an extra check in the PR, but maybe it's also worth to add some notice to wiki.
Clearly that is not a great solution, but best I could think of at the moment. If I had time then I would try to rewrite it to use python schedule module.

https://github.com/Der-Henning/tgtg/pull/365

In addition, during testing, I've noticed that in MakeFile:
```bash
python -m pytest ...
```
I changed to python3 by default, if not available rollback to python.

Greetings,
Wojciech

**Comment by Der-Henning** [comment]
Hi @punfil.
Thank you for your contribution.
Actually, the cron scheduler is meant to limit the time ranges in which the scanner is running. It should not trigger the scanning process.
The idea is to set something like `* 6-22 * * 1-5` to scan only on workdays between 6:00 and 23:00.
I know that it can be a bit confusing, as it allows to set something like `*/2 * * * *`, which is not the intended use case.
Please let me know if you have any good ideas to make this clearer.

**Comment by Der-Henning** [comment]
Closing as described in #365.
