### ISSUE TITLE
Error with DockerCompose

### ISSUE THREAD

**Issue by Hazza197** [Der-Henning/tgtg#368]
Hi,

I'm trying to run the TGTG Notifier through Docker, I've used the stack which was in the repository and tweaked for my setup. Every time I create the stack the Container attempts to start but fails with Error 443. I've attached the log below - could someone give me some advice on getting this up and running please?

[_tgtg-app-1_logs.txt](https://github.com/Der-Henning/tgtg/files/11724635/_tgtg-app-1_logs.txt)

**Comment by Der-Henning** [comment]
Hi @Hazza197.
Your container cannot resolve the connection to the domain `api.github.com`, which is used to check for the latest version.
This shouldn't be an issue and only create an appropriate warning message. I will fix that.
But when your container cannot connect to the GitHub API it would probably not be able to connect to the TGTG API. Is your docker running behind any kind of proxy network?

**Comment by Hazza197** [comment]
So I wiped my Docker Install - it was an issue my side with the filesystem being a nightmare.

I've managed to get the Container up and running so will follow though with the setup - thank you for you help.

**Comment by Der-Henning** [comment]
I'm glad it is working for you now.
As of Release v1.17.0, the observed error only creates a warning.
Closing.
