### ISSUE TITLE
Text failure

### ISSUE THREAD

**Issue by Wolbaal** [Der-Henning/tgtg#378]
Hi, just noticed that there is a little text failure, there is "mafic" instead of magic.

Reserve the next available mafic bag 

In telegram

**Comment by bisselch** [comment]
I've corrected it in my [pull request](https://github.com/Der-Henning/tgtg/pull/373).

**Comment by Der-Henning** [comment]
The typo is now fixed in the dev branch and will be part of the next release. 
Closing.
