### ISSUE TITLE
explanation reservation needed

### ISSUE THREAD

**Issue by edkowalski9** [Der-Henning/tgtg#384]
Ok i feel quite stupid but i seem not to be able to figure out how the reservation works.
It would be great if i can getter an explanation.

 Im able to us the /reserve command. I get a list and i choose.
The bag is then also displayed with the /reserved command.

Now this is where it goes not well.

How to unreserve? When it is reserved, it is also removed from the list when i use the /reserved command (or at least that's how it looks to me).

If I add it to the list again, I'm getting in a cycle. It gets released after 5 min, and gets reserved again. So that's not the solution. 

If I wait 5 min, it gets unreserved automatic;y and I can quickly buy it. 

So, how to unreserve if it is already gone from the /reserved list?

I'm doing smth wrong, but what it is.....

Thx  in advance.

**Comment by edkowalski9** [comment]
![Screenshot 2023-06-29 113417](https://github.com/Der-Henning/tgtg/assets/138111329/c10fdf8b-e31b-4e60-90d5-8b262b54714d)

Here is a picture were you can see the reservation made, but its not on the list anymore. So how to unreserve.

**Comment by Marcel-NL1963** [comment]
Just click on the line you want to unreserve.

**Comment by Marcel-NL1963** [comment]
You're right, I overlooked that. Strange...

**Comment by bisselch** [comment]
Please check the explanation in the [wiki](https://github.com/Der-Henning/tgtg/wiki/FAQ#4-how-does-the-reservation-feature-work).

**Comment by edkowalski9** [comment]
Thnx, this was the info I needed!

**Comment by PB91-FR** [comment]
does this mean that you have to wait 5 mins to buy the basket?

**Comment by Der-Henning** [comment]
Hi @PB91-FR.
With /orders you can see all triggered reservations and cancel them by clicking on it. Or you can use /cacelall to cancel all triggered reservations at once.

**Comment by PB91-FR** [comment]
I undertand. Thanks a lot.

**Comment by michaelmhtong** [comment]
Hi @Der-Henning 
I'm also wondering if, when I release the bag, it's only available for me again, or can someone else take it during that period?

Thanks for build this amazing notification btw!
