### ISSUE TITLE
Orders command not working

### ISSUE THREAD

**Issue by scaryMikrowelle** [Der-Henning/tgtg#388]
Hey,
I'm using the tgtg scanner on my pi via docker and connected telegram to it.
It works great but the /orders command always shows "no active orders" even tho I have ones.

Thanks

**Comment by floriegl** [comment]
Did you read https://github.com/Der-Henning/tgtg/wiki/FAQ#4-how-does-the-reservation-feature-work ? /orders only displays "all triggered and active reservations" and not any orders. I also find this a bit hard to get but this tgtg notifier does not support creating orders or viewing orders, just creating reservations, so other people (and you) are blocked from buying the magic bag until you release the reservation.

**Comment by scaryMikrowelle** [comment]
Ohh that's what it means. Thank you!
