### ISSUE TITLE
Telegram Error: connection abortet // no reservation

### ISSUE THREAD

**Issue by LikeyX** [Der-Henning/tgtg#398]
Telegram Error: connection abortet

I receive the message via Telegram even with this message (it appears on bag amount change, with and without reservation). But reservation isnt working.

![image](https://github.com/Der-Henning/tgtg/assets/27165564/d7fac1b0-f401-4ffd-9358-dcf225c3737e)

**Comment by floriegl** [comment]
Can you maybe enable Debug in your configuration (see https://github.com/Der-Henning/tgtg/wiki/Configuration) and check if you can get more details about your problem that way? Just to make sure: Only run one bot instance with one Telegram bot token.

**Comment by LikeyX** [comment]
Tried today, no issue anymore. Dunno what that was. I close it here - the "no reservation" got opened by someone else already
`
