### ISSUE TITLE
Reservation feature not working

### ISSUE THREAD

**Issue by dissidente** [Der-Henning/tgtg#411]
Hi.

First of all let me thank you for a great project. I was looking for this for quite some time but didn't quite like what I was finding until I found your project =)

I'm running it on Synology NAS through a Docker container (v 1.17.1 currently). Notifications seem to work just fine (although I have noticed that rarely it misses some; didn't look into that yet, as I only realized it last Wednesday, so don't worry about this (yet)).

I do however have an issue with the reservation feature, which in my case doesn't work at all. Two way communication with the bot seems ok, as I can list the reservation and order queue (which are always empty, of course, but I do get a reply from the issued commands), but when I issue a reservation command I don't get anything back.

I enabled debug mode to troubleshoot it, and I managed to find out that the issue is that the markup reply is too long:

![Screenshot_20230909_113014_Chrome](https://github.com/Der-Henning/tgtg/assets/63504146/386e202c-6d1e-40eb-abb3-48a599c983bb)

Now, I feel this has something to do with my TELEGRAM_BODY variable, which is a bit costumized:

`🥡 *\-\=\[ TooGoodToGo Notifier \]\=\-* 🥡\n\n*${{display_name}}* \n\n*Category*: ${{item_category}}\n*Available*: ${{items_available}}\n*Price*: ${{price}} ${{currency}}\n*Pickup*: ${{pickupdate}}\n*Rating*: ${{rating}}\n\n*Location*: ${{pickup_location}}\n*Link*: ${{link}}`

Am I right? If so, any way to workaround this besides cutting it short? =\

Thanks in advance!

**Comment by lilok** [comment]
Hello,

excuse me i would like to ask a clarification about the "Reservation feature". For what i can see reservation in the app requires a payment. What is the logic of reservation through Too Good Too Scanner? When reserved an order how does it should appear in the app? Waiting for payment? I use TGTG from Italy.

Thanks, regards

**Comment by olzhang** [comment]
Hi,

I propose a feature where the body of the notification is different than the body of the messages that come from the reservations feature? When I wanna reserve a bag, I know exactly the restaurants that I wanna reserve from so i can do with a smaller body, but when I get notifications, I wanna see more info

Cheers

**Comment by olzhang** [comment]
It's not your telegram body, your favorite list is too long 

https://github.com/Der-Henning/tgtg/blob/main/tgtg_scanner/notifiers/telegram.py#L198

**Comment by dissidente** [comment]
The issue was indeed the favorite list being too long. After shortening it the issue was resolved
