### ISSUE TITLE
Price showing 0.00

### ISSUE THREAD

**Issue by pershoot** [Der-Henning/tgtg#433]
Hi @Der-Henning .

I wanted to notify you of an issue which just started occurring (~45minutes ago).

Price is now showing 0.00:
Price: 0.00 -

Using built from source against v1.18.0_rc3.

However, I'll keep monitoring to see if it is a temporary issue on the source's side and resolves.

Thank you.

**Comment by Der-Henning** [comment]
Hi @pershoot.
I also noticed this behavior. The api responses didn't include the `price_including_taxes`. But it seems to be a temporary issue, as everything is working again. Can you confirm?

**Comment by pershoot** [comment]
Yup @Der-Henning , confirmed; price has been restored.

Thank you.

**Comment by BertHG** [comment]
Hi

Same error here, for the whole day so it seems to be a recurring issue

**Comment by Der-Henning** [comment]
@BertHG Yep. I guess 2 days ago they tested the new API configuration.
Now they changed it.
Not a big hack to update the scanner.
I will update the code today and try to make a new release asap.

**Comment by pershoot** [comment]
Thank you @Der-Henning for your efforts.

**Comment by pershoot** [comment]
@Der-Henning I'm testing DEV.  Seems ok, thus far.

**Comment by pershoot** [comment]
@Der-Henning Hi.  No issues observed; switched to main.  Thank you.

**Comment by Der-Henning** [comment]
Release 1.18.0 contains the fix for this issue. Closing again.
