### ISSUE TITLE
Container crash on start after upgrading from v1.17.1 to latest version

### ISSUE THREAD

**Issue by dissidente** [Der-Henning/tgtg#438]
Hi.

I just updated the docker container to the latest version, and now the container crashes on start with the following messages:

```
Updating UID and GID to 1000:1000
usermod: no changes
python: can't open file '//main.py': [Errno 2] No such file or directory
```

I've enabled the debug flag but no additional information is returned.

Any idea of how to solve this issue?

Thanks in advance

**Comment by Der-Henning** [comment]
Hi @dissidente.
Can you please provide your container configuration? Did you define a custom start command? The new command to start the scanner is `python -m tgtg_scanner`. But you don't have to set is as it is already part of the image. For a basic configuration see [`docker-compose.yml`](https://github.com/Der-Henning/tgtg/blob/main/docker-compose.yml).

**Comment by dissidente** [comment]
Ok, that is it.

I'm running the container on Synology NAS, and the usual container image update involves downloading the new version of the container (as it's using the latest tag) and resetting the container. This of course doesn't change the start command, so when you changed the start command, following this update procedure, it didn't work as expected.

Removing the container and creating a new one and adding the custom configuration settings did the trick.

Thanks =)
