### ISSUE TITLE
Telegram chat id is missing

### ISSUE THREAD

**Issue by skinner13** [Der-Henning/tgtg#441]
Hi together,

I will setup the telegram notifier. In old versions there was not a problem but since a few days I have problems. Normaly the chat id is automaticly created after entering the Token. Now nothing happens and the chat id is always empty.

When I read the id by t.me/myidbot and entering this number in config file I got the message "No Chat found".

![grafik](https://github.com/Der-Henning/tgtg/assets/141318532/958d763d-da58-43f1-8866-fa22568d4606)

![grafik](https://github.com/Der-Henning/tgtg/assets/141318532/4d240798-f839-4b7c-9497-7d4f67daa8cb)

Anyone an idea?

br Jan

**Comment by Der-Henning** [comment]
Hi @skinner13.
Did you try to remove the `ChatIDs` option from the config? When no chat id is configured the bot should ask you to enter a code in your chat to obtain the chat id.

**Comment by ColinusM** [comment]
that worked thank you
