### ISSUE TITLE
Config not being parsed correctly from docker-compose file

### ISSUE THREAD

**Issue by abbashtz** [Der-Henning/tgtg#451]
I have been using the same docker-compose file for over a year however when I upgrade to v1.18 push safer stops working.
Additionally logs show that Telegram notifier is enabled even though the compose file does not enable it. (It should be disabled by default)

Versions tested: 
1) v1.20 - Same as v1.18
**2) v1.18 - Push safer not working / Telegram notifier enabled but should be DISABLED**
3) v1.17.1 - Working fine
4) v1.16 - Working fine

Based on my testing it seems something got introduced between v1.17.1 and v1.18 which is causing this.

I have attached my docker-compose file and some logs of the highlighted version.
My username and push safter token is obfuscated.

Not sure what the root cause is but two observations:
1) Push safer not working
2) Telegram notifier is shown as enabled in logs -> but it is not enabled in docker-compose

[Error TGTG.txt](https://github.com/Der-Henning/tgtg/files/13998968/Error.TGTG.txt)
[docker-compose text.txt](https://github.com/Der-Henning/tgtg/files/13998973/docker-compose.text.txt)

**Comment by Der-Henning** [comment]
Hi @abbashtz 
I renamed the environment variables for the push safer configuration to `PUSHSAFER_` for consistency reasons.
But I failed to update the documentation and add a depreciation notice ...
The bugfix and documentation update will be released as soon as possible.
Changing `PUSH_SAFER_` to `PUSHSAFER_` should already work.
The Telegram issue should be solved with version 1.20.0. Can you confirm that it is still an issue with that version?

**Comment by abbashtz** [comment]
Hi @Der-Henning 
I've updated to v1.20 and updated the variable as recommended above.
Can confirm that both observations are resolved.

I am closing this issue with this comment. Thanks!
