### ISSUE TITLE
adding and removing items from favorites does not work anymore

### ISSUE THREAD

**Issue by floriegl** [Der-Henning/tgtg#459]
It looks like TGTG changed their API which now return 404 on `https://apptoogoodtogo.com/api/item/v8/{item_id}/setFavorite`

As I have no experience with reverse engineering mobile APIs I sadly can't support with fixing this issue.

Log from my instance with debug enabled (also shows that other requests work):
![image](https://github.com/Der-Henning/tgtg/assets/22279483/b3e39f59-9103-47fa-9169-c9618b05a369)

https://github.com/ahivert/tgtg-python/issues/288 Looks like someone in a different repo with a TGTG client also has the same issue.

Edit: Did some Android MITM. The new Endpoint is POST /api/user/favorite/v1/{item_id}/update with body {"is_favorite":true} or  {"is_favorite":false}

**Comment by Der-Henning** [comment]
Hi @floriegl.
Thank you for your contribution.
The new release 1.20.2 contains the update.
