### ISSUE TITLE
Beginner question

### ISSUE THREAD

**Issue by oryinchan** [Der-Henning/tgtg#463]
I would like to monitor the item https://share.toogoodtogo.com/item/1078196 with my telegram bot.

It's totally new to me, sorry for the lack of knowledge ,can anyone show me the example of whole value for the TELEGRAM_BODY?

**Comment by pershoot** [comment]
Add that item to your favorites.
- Body = *${{display_name}}*\n*Available*: ${{items_available}}\n*Rating*: ${{rating}}\n*Price*: ${{price}} ${{currency}}\n*Pickup*: ${{pickupdate}}\n*Link*: ${{link}}
