### ISSUE TITLE
tgtg scanner for linux aarch64 arm

### ISSUE THREAD

**Issue by tasty3** [Der-Henning/tgtg#49]
HI,
I would like to put the application on Oracle free tier cloud "always free" for Arm Ampere A1 Compute : scanner-linux-v1.6.0.
The executable "scanner" is for x86-64 and does not work for aarc64 Arm.
Can you add a version compatible with this platform ?
Thanks

**Comment by Der-Henning** [comment]
Hello,
The executables are meant for use on desktop as a quick start solution for none technical users. 
If you want to set it up on a server I recommend using the [docker images](https://hub.docker.com/r/derhenning/tgtg) (build for amd64, armv7 and arm64). Or, if you don't want the overhead of a docker installation, install python 3.9+, clone this repo, install dependencies and run the scanner.py. 
[run-from-source documentation](https://github.com/Der-Henning/tgtg#run-from-source)

**Comment by tasty3** [comment]
I configured the file "config.ini" in src however when I run it writes this :

File "scanner.py", line 73
    raise TGTGConfigurationError() from err
                                      ^
SyntaxError: invalid syntax

**Comment by Der-Henning** [comment]
can you please provide the full log?

**Comment by tasty3** [comment]
I do not know how to do.

**Comment by Der-Henning** [comment]
you can copy the output in the console or copy it from the scanner.log file and past it here.

**Comment by Der-Henning** [comment]
closed due to inactivity

If the problem still exists feel free to reopen the issue or create a new one
