### ISSUE TITLE
Regex for webhook notifier to replace variables is not correct

### ISSUE THREAD

**Issue by floriandrott** [Der-Henning/tgtg#50]
The regex for replacing the variables in the webhook notifier is not correct. The variable names have an `_` included and the regex is not taking the `_` into account.

**Comment by Der-Henning** [comment]
OK. The webhook doesn't work at all... I will fix it asap.

**Comment by floriandrott** [comment]
@Der-Henning with the latest build the webhook is not working due to an error in the item subscription. With `v1.6.0` the webhook is working but not with the variables.

**Comment by Der-Henning** [comment]
@floriandrott I updated the webhook notifier. Can you please verify if it is working now for your use case?

**Comment by floriandrott** [comment]
@Der-Henning works for me :) Thank you very much for the help.
Just one side note. The variable content is including `"` at the beginning and end. For me that's perfectly okay but I'm not sure if we should add this to the documentation. If you agree I can create a pull request for the change.

**Comment by Der-Henning** [comment]
@floriandrott Thats great. 
Yes you are right and documentation is always a big issue. Feel free to contribute. Thanks.
Closing this issue now.

**Comment by Der-Henning** [comment]
Update:
75e54df removes the extra ```"```. This will be included in the next release but is already in the latest docker image.
Please update your config accordingly.
