### ISSUE TITLE
Gmail SMTP password not taken

### ISSUE THREAD

**Issue by wimgielis** [Der-Henning/tgtg#517]
Hello,

I am trying to run the tool and updated the config.ini file.
When starting the scanner, I get the error:

[2024-07-14 00:43:05][tgtg][__main__.py:main:217][ERROR] Configuration Error: (534, b'5.7.9 Application-specific password required. For more information, go to\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor ffacd0b85a97d-368119970e7sm1809147f8f.21 - gsmtp')

I know for a fact that my password for Gmail is correct. It does have an ampersand, is that an issue ? Do we need to escape it ?
The last version is used (a day old). I cannot compare with earlier versions, first time user here :-)

Thanks a lot !

Wim

**Comment by wimgielis** [comment]
Or, does it have to do with 2FA ?

**Comment by Der-Henning** [comment]
Hi @wimgielis,

You need to create an application password for your google account.

https://support.google.com/accounts/answer/185833?hl=en

**Comment by wimgielis** [comment]
Okay thanks. I will do that and report back. Enjoy your Sunday !


------

Best regards / Beste groeten,

Wim Gielis
IBM Champion 2024
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op zo 14 jul 2024 om 07:48 schreef Henning Merklinger <
***@***.***>

**Comment by wimgielis** [comment]
The scanner is active, thanks for the assistance.
