### ISSUE TITLE
Too many captcha Errors! 

### ISSUE THREAD

**Issue by Omg974** [Der-Henning/tgtg#523]
Hi,

I have a problem with TGTG synology contenair (latest)
Ihave this message: 
2024/08/04 18:25:16	stdout	[36m2024-08-04 16:25:16[0m [33mWARNING [0m Too many captcha Errors! Sleeping for 10 minutes...[0m
2024/08/04 18:25:05	stdout	[36m2024-08-04 16:25:05[0m [32mINFO    [0m Retrying ...[0m
2024/08/04 18:15:05	stdout	[36m2024-08-04 16:15:05[0m [33mWARNING [0m Too many captcha Errors! Sleeping for 10 minutes...[0m
2024/08/04 18:14:55	stdout	[36m2024-08-04 16:14:55[0m [32mINFO    [0m Retrying ...[0m

Somebody have a solution ?

Thanks !!

**Comment by chrematt** [comment]
What did resolve the issue?

**Comment by Omg974** [comment]
Nothing, need to be patient
