### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by jeroendew** [Der-Henning/tgtg#53]
Hi,

Is it possible to integrate telegram?

**Comment by tomekk3108** [comment]
Hi @jeroendew . Yesterday I sit on that and added support for Telegram. I created pull request for that.
https://github.com/Der-Henning/tgtg/pull/54

**Comment by Der-Henning** [comment]
@tomekk3108  Thank you for your work!
Telegram support integrated with PR #55 into main branch. 
New release v1.7.0 will include the Telegram support and will be release tomorrow.

**Comment by Der-Henning** [comment]
Released Version 1.7.0 with telegram support. Closed.
