### ISSUE TITLE
Telegram body direct link to TGTG app

### ISSUE THREAD

**Issue by mbaruzzo** [Der-Henning/tgtg#544]
Hi! 

I am not sure if this was already posted but I could not find it.
I used to have in the environment tab of the docker under TELEGRAM_BODY the following

*${{display_name}}*\n*Available*: ${{items_available}}\n*Rating*: ${{rating}}\n*Price*: ${{price}} ${{currency}}\n*Pickup*: ${{pickupdate}}\n*Link*: https://share.toogoodtogo.com/item/${{item_id}}

Now it seems it doesn't work anymore as the link contains "."

If I remove the link part "\n*Link*: https://share.toogoodtogo.com/item/${{item_id}}" it works perfectly but then I don't have the direct link to go the app.
Is it something that can be added in a different way perhaps?

Thanks.

**Comment by nevrrmind** [comment]
Try: \n*Link*: ${{link}}

**Comment by mbaruzzo** [comment]
> Try: \n_Link_: ${{link}}

it worked thanks!
