### ISSUE TITLE
API update

### ISSUE THREAD

**Issue by tobeginbegin** [Der-Henning/tgtg#556]
Hi,

It looks like the API has updated so when I try to connect I get an API error. Looks like API V3 is deprecated. Does anyone know how to fix this? Appreciate it!

**Comment by Shughen85** [comment]
Same issue there : 
2024-11-22 18:50:32 ERROR    TGTG API Error: (404, b'{"type":"about:blank","title":"Not Found","status":404,"detail":"No static resource auth/v3/token/refresh.","instance":"/api/auth/v3/token/refresh"}')


Appreciate it as well ;)

**Comment by antonioli86** [comment]
Some updates here:
https://github.com/ahivert/tgtg-python/pull/324

**Comment by antonioli86** [comment]
At first glance seems we need to update the endpoint from v3 to v4 in these files:
https://github.com/search?q=repo%3ADer-Henning%2Ftgtg%20auth%2Fv3%2FauthByEmail&type=code

Based on this:
https://github.com/ahivert/tgtg-python/pull/324/commits/7bd3bbbefb9397776855cadb53e6149e83ceed63

**Comment by Der-Henning** [comment]
I just released v1.22.0 including the api update.
