### ISSUE TITLE
Only sends one notification at start

### ISSUE THREAD

**Issue by TouffeTouffe** [Der-Henning/tgtg#563]
After startup, only one notification is sent in console or discord webhook. With debug enabled, the program does register a new state with another basket when available, but never sends another console or webhook notification.

**Comment by Der-Henning** [comment]
Hi @TouffeTouffe.
Yes this is the intended behaviour. The scanner send one Test notification at startup so you can check if everything is set up correctly. You can disable this notification with `DISABLE_TESTS=true`.
The scanner than only sends notifications when the amount of available bags raises from zero to something.
If you want more complex notifications feel free to use the metrics endpoint in combination with prometheus and an alert manager.

**Comment by TouffeTouffe** [comment]
Correct. The issue is only on startup: if there are more than one basket available (let's say N), only one notification is sent instead of N. Can be marked as a feature request if not a bug.
