### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by er-Sax** [Der-Henning/tgtg#6]
Invalid syntax in line 63 

  File "scanner.py", line 63
    def _check_item(self, item: Item):
                                            ^
SyntaxError: invalid syntax

Operating system Linux (debian 8.11), python version 2.7.9

**Comment by Der-Henning** [comment]
Python type hints are supported for python > 3.5. I work on Python 3.9 so this is the only tested and supported version.

**Comment by er-Sax** [comment]
Thx
