### ISSUE TITLE
TGTG API Error: 403 (recaptcha)

### ISSUE THREAD

**Issue by jeroendew** [Der-Henning/tgtg#61]
I think it was fun as long as it lasted, or do you have a solution in mind?
`2022-02-17 11:59:33 ERROR    TGTG API Error: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={\'cid\':\'AHrlqAAAAAMAZo-yyBw10l8AkTX8xA==\',\'hsh\':\'1D42C2CA6131C526E09F294FE96F94\',\'t\':\'fe\',\'r\':\'b\',\'s\':35558,\'host\':\'geo.captcha-delivery.com\'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n')`

**Comment by mjoerg78** [comment]
Same for me. I had the request rate at 5s. After restarting the scanner 6 hours later it worked again. So it seems tgtg blocks connections that query to often.
