### ISSUE TITLE
Script don't read docker-compose.yml in docker

### ISSUE THREAD

**Issue by luchtbakker** [Der-Henning/tgtg#69]
Hello.

I've placed docker-compose.yml (and edited, ofcourse) in the right folder, but the script gives error:  Unexpected Error! - (<class 'TypeError'>, TypeError('You must provide at least email or access_token, refresh_token and user_id'), <traceback object at 0x7f8599d4f980>)

File placed in /var/lib/docker/containers/04f596f96f2613227932f1d29335f968b21303293d33be42ccdd111780f70fbb/

After running: docker-compose up -d the error: 

ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml

what i'm doing wrong?
I'm new with docker, i'm sorry if i'm doing things wrong.

**Comment by Der-Henning** [comment]
Hi. You have to run ```docker-compose up -d``` from the directory you placed your ```docker-compose.yml```.
You don't have to place it in the docker ```/var``` folder. Simply create it in your home folder.

**Comment by luchtbakker** [comment]
Great! It works.

Thank You Very Much!
