### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Wolbaal** [Der-Henning/tgtg#84]
Hi, have some issues with the program and is there an option that I can contact you to send some screenshots?

**Comment by Der-Henning** [comment]
Hi @Wolbaal.
Please create an issue here on github. You can add screenshots via drag and drop.
Any issue discussed publicly is valuable as it helps others with similar problems find solutions quickly.
So don't hesitate to open new issues.

**Comment by Wolbaal** [comment]
Thanks for reply.

I've got a bunch of error's 
Urllib3 HTTPerror external host has broken the connection. (It's in windows (scanner v1.9.0)

Now I did a setup on rpi4 and pulled down the docker. But now I need to know how I can change the settings in the config file? Hope you can help me on the way

**Comment by Wolbaal** [comment]
![image](https://user-images.githubusercontent.com/103828692/164272081-b7609d40-c1cc-453a-9483-bce10be9bebe.jpeg)

**Comment by Der-Henning** [comment]
Sorry for my late reply. I am very busy these days ...

Using docker and docker-compose you don't need to create a `config.ini`. Referring to the [Readme](https://github.com/Der-Henning/tgtg#run-with-docker) you should define the config as environment variables as described in the [`docker-compose.yml`](https://raw.githubusercontent.com/Der-Henning/tgtg/main/docker-compose.yml). It should be as simple as creating the `docker-compose.yml`, filling in the required configurations and running `docker-compose up`. `docker-compose up -d` for detached mode so you can close the terminal. 

Can you please provide more content of the log file so I can try to reproduce the error? You can just copy&paste it here or upload the scanner.log. Don't forget to delete or mask your credentials.

**Comment by Wolbaal** [comment]
Thanks for reply, no problem.

I did oversee the yml file, but now I created as mentioned and uploaded to the rpi. But now I get the following:
![image](https://user-images.githubusercontent.com/103828692/164721993-b15dc24c-c745-46c5-a4b3-fc8e2a08e19b.jpeg)
Did check the time, but has already the local time.
Do you know how to fix?

About the log file of the error, this is on windows and doesn't has an option to upload and copy paste doesn't work unfortunately.

**Comment by Der-Henning** [comment]
OK. So everything is working I guess. closing.
Feel free to create a new issue if you have any problems.
