### ISSUE TITLE
TGTG API Error: 403

### ISSUE THREAD

**Issue by vipera7** [Der-Henning/tgtg#93]
Hello,

I'm running tg notifier through docker compose using the latest version (1.10.1). The bot was running smoothly since weeks and I upgraded it to the latest version, and I'm facing the following error : 

> [root@localhost toogoodtogo]# docker logs toogoodtogo_app_1
> 2022-05-18 16:40:55 INFO       ____  ___  ____  ___    ____   ___   __   __ _  __ _  ____  ____
> 2022-05-18 16:40:55 INFO      (_  _)/ __)(_  _)/ __)  / ___) / __) / _\ (  ( \(  ( \(  __)(  _ \
> 2022-05-18 16:40:55 INFO        )( ( (_ \  )( ( (_ \  \___ \( (__ /    \/    //    / ) _)  )   /
> 2022-05-18 16:40:55 INFO       (__) \___/ (__) \___/  (____/ \___)\_/\_/\_)__)\_)__)(____)(__\_)
> 2022-05-18 16:40:55 INFO
> 2022-05-18 16:40:55 INFO     Version 1.10.1
> 2022-05-18 16:40:55 INFO     ©2021, Henning Merklinger
> 2022-05-18 16:40:55 INFO     For documentation and support please visit https://github.com/Der-Henning/tgtg
> 2022-05-18 16:40:55 INFO
> 2022-05-18 16:40:55 INFO     Loaded config from environment variables
> 2022-05-18 16:40:55 ERROR    TGTG API Error: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={\'cid\':\'AHrlqAAAAAMANsAP9ysHbxEA2aA2Pw==\',\'hsh\':\'1D42C2CA6131C526E09F294FE96F94\',\'t\':\'fe\',\'r\':\'b\',\'s\':35558,\'e\':\'d930abc479b69a47d56bbc894c7f3fc8d5c47ef8fefcef7c1786c1502abd2f5b\',\'host\':\'geo.captcha-delivery.com\'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n')

Do we need to wait a new version to bypass the captcha ?

Thanks

**Comment by vipera7** [comment]
I'm running the container on a VPS. 
Here is my **docker-compose.yml**

```
version: "3.3"
services:
  app:
    image: derhenning/tgtg:latest         ## pre build image from docker hub
    #image: tgtg-scanner:latest           ## locally build image
    environment:
      - TZ=Europe/Paris                               ## Set timezone for pickupdate, otherwise will be utc
      - DEBUG=false                                   ## true for debug log messages
      - TGTG_USERNAME=SECRET@example.com       ## TGTG Username / Login EMail
      - SLEEP_TIME=60                                 ## Time to wait till next scan in seconds - default 60 seconds
      - ITEM_IDS=1,2,3,4                                     ## (optional) Comma seperated list of Item Ids to scan
      - METRICS=false                                 ## Enable to export metrics for Prometheus
      - METRICS_PORT=8000                             ## Port for metrics http server
      - DISABLE_TESTS=false                           ## true to disable test notifications on startup

      - SMTP=false                                    ## true = enable mail notifications via smtp
      - SMTP_HOST=smtp.gmail.com                      ## smtp Server - smtp.gmail.com for google
      - SMTP_PORT=465                                 ## smtp Server Port - 465 for google
      - SMTP_USERNAME=max.mustermann@gmail.com        ## smtp Login - your EMail for google
      - SMTP_PASSWORD=                                ## smtp Login Password - your Login PW for google
      - SMTP_TLS=true                                 ## enable TLS - true for google and most smtp servers
      - SMTP_SENDER=max.mustermann@gmail.com          ## sender adress - same as Login for google and most smtp servers
      - SMTP_RECIPIENT=max.mustermann@gmail.com       ## recipient for notifications - can be the same as sender

      - PUSH_SAFER=false                              ## true = enable notifications via pushsafer.com
      - PUSH_SAFER_KEY=
      - PUSH_SAFER_DEVICE_ID=

      - TELEGRAM=true                                 ## true = enable notifications via Telegram
      - TELEGRAM_TOKEN=SECRET                               ## Telegram Bot token - see @botfather
      - TELEGRAM_CHAT_IDS=-SECRET                            ## Telegram Chat id, multiple ids separated by comma
      #- TELEGRAM_BODY=                               ## Optional message body as markdown, variables as described below
                                                      ## Example:
                                                      ## 'TELEGRAM_BODY={{`*$${{display_name}}*\n*Available*: $${{items_available}}\n*Rating*: $${{rating}}\n*Price*: $${{price}} $${{currency}}\n*Pickup*: $${{pickupdate}}`}}'

      - IFTTT=false                                   ## true = enable notifications via IFTTT Webhooks
      - IFTTT_EVENT=tgtg_notification                 ## IFTTT Webhooks Event
      - IFTTT_KEY=                                    ## IFTTT Webhooks Key

      ## Possible $${{variable}} variables: item_id, items_available, display_name, price, currency, pickupdate
      ## Example:
   ## - 'WEBHOOK_BODY={"message": "$${{display_name}} - New Amount: $${{items_available}}", "priority": 2, "title": "New TGTG Items"}'
      ## Notice that you have to enclose the variable with ''
      - WEBHOOK=false                                 ## true = enable notifications via costum WebHook
      - WEBHOOK_URL=                                  ## URL of your WebHook, can contain $${{variable}}
      - WEBHOOK_METHOD=POST                           ## Request Method
      - WEBHOOK_BODY=                                 ## Data to send, can contain $${{variable}}
      - WEBHOOK_TYPE=                                 ## Content-Type for header, default: text/plain
      - WEBHOOK_TIMEOUT=60                            ## Request Timeout
    volumes:
      - /home/tgnotifier/tokens:/tokens           ## volume to save TGTG credentials to reuse on next start up and avoid login mail
volumes:
  tokens:
```

Do I have to increase the `SLEEP_TIME` ? I don't think it will resolve because the container is running like 4-5 seconds before exiting. Do I need to reboot the VPS ?

Thanks

**Comment by Der-Henning** [comment]
A `SLEEP_TIME` of 60 should be fine and normally doesn't trigger the "too many requests temporary ban" of the TGTG API.
Rebooting is always a good and cheap way to magically solve any problems :) So it is worth a try.
Usually the 403 is only a temporary ban that is resolved after some hours. 
But you can try using a new IP if it is possible for your VPS.

**Comment by vipera7** [comment]
Thanks, I rebooted but I'm facing the same issue. I'll give a try tomorrow

**Comment by vipera7** [comment]
Thanks, I rebooted but I'm facing the same issue. I'll give a try tomorrow

**Comment by vipera7** [comment]
It's working now. Thanks for the help !
